In [53]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0521(final)/data/process/process2/process2 test data row.csv",index_col=0)

In [54]:
data_row

                                               sentence  predict
1385       아 네 예 알겠습니다. 조금만 기다려 전화는 호주머니에 넣고 이동하시겠습니다 네        1
646    어디에 상환하신거... 수요일에 상환하신..아닌데 잠시만요 목요일날 상환하신거 말...        0
423    서울 중앙 지검 검찰청이요. 그 중앙 하단 쪽에 보이면 그 파란색 박스 안에 나의...        1
377    위임 처리하시면 당일로도 가능하시고 위임을 하면 어떻게 되요? 위임하실 경우에는 ...        0
482    예 말씀 드리는 거 말씀 드리는데 집중을 안 하시는 거 같다고요 아 예 집중하실 ...        0
...                                                 ...      ...
632     저희가 인제 조사 내용을 녹취를 할 건데요  저 아까 어디소속 누구라고 말씀하셨...        1
853                             잠깐만 갑자기 생각이 안 나네.  요? 예        0
1291                                       김기훈 예 명의도요 예        1
393    그러시고 다른 계좌 건. 다른 것도 다 제가 한거에요. 다른 계좌건 어떤 계좌건 ...        1
1496   그때 제가 절차 다 질문 드리면 본인께서는 아시는 대로 진술을 해주시면 되는겁니다...        1

[200 rows x 2 columns]

In [55]:
data_row.isnull().sum()

sentence    0
predict     0
dtype: int64

In [56]:
data=data_row.sample(frac=1)

In [57]:
data

                                               sentence  predict
528    네 알겠습니다. 만일 조사 결과 내용이 뭐 본인이 말씀하신거랑 다를 경우 사기 방...        1
902                예 그럼 바로 해주세요 바로 위임 처리로 진행을 도와드릴까요? 예        0
1146        음 두개 사용도는 뭐가 어떻게 되시니까요 네? 사용 용도가 가까워요 아 그니까        1
51     20만원 먼저 넣어라 이건 아닌거 같은데요? 그래서 말씀 드리잖아요. 20만원 넣...        0
1082                      왜 말이 없어요. 어 진짜... OOO씨. OOO씨.        1
...                                                 ...      ...
416    잠시만요 제 생년월일 말하고요? 네 성함 생년월일. OOOOO 계좌 이체 추적을 ...        1
1226   문자 본인 앞으로 나와있는 정보 확인하시고요. 아 지워져 쓰면은 네 네 지웠어요 ...        1
749    뭐가 생겼어요? 서로간의 믿음성이 선생님도 그렇게 하면은 그냥 한번 그쪽 때문에 ...        1
961    듣고 있어요. 자 일단 재녹취 진행할 테니까 전화 바로 할게요. 들어가지 마세요. 네?        1
409               사기범 :\u3000네 피해자 :\u3000하나는 679872원 네        1

[200 rows x 2 columns]

In [58]:
data.to_csv("process2 test data before nlp(base).csv")

In [59]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

In [60]:
data.isnull().sum()

sentence    0
predict     0
dtype: int64

In [61]:
A=model.encode(data.iloc[0,0])

In [62]:
A.shape[0]

768

In [63]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [64]:
x_train=pd.DataFrame(index=range(0,data.shape[0]),columns=list)

In [65]:
x_train.shape

(200, 768)

In [66]:

y_train=pd.DataFrame(index=range(0,x_train.shape[0]),columns=['predict'])

In [67]:

x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
y_train

    predict
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
..      ...
195     NaN
196     NaN
197     NaN
198     NaN
199     NaN

[200 rows x 1 columns]

In [69]:
for i in range(data.shape[0]):
    y_train.iloc[i,0]=data.iloc[i,1]

In [70]:
y_train

    predict
0         1
1         0
2         1
3         0
4         1
..      ...
195       1
196       1
197       1
198       1
199       1

[200 rows x 1 columns]

In [71]:
y_train.isnull().sum()

predict    0
dtype: int64

In [72]:
for i in range(data.shape[0]):
    vector=[]
    vector=model.encode(data.iloc[i,0])
    for j in range(x_train.shape[1]):
        x_train.iloc[i,j]=vector[j]

In [73]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.08059,0.003355,-0.021159,0.016135,0.011212,0.00094,-0.001987,0.008926,0.044516,-0.03038,...,0.006629,0.005829,-0.000782,0.009129,-0.061586,-0.102544,0.013484,0.031701,0.023892,-0.040797
1,0.064557,-0.071604,-0.01181,0.012967,0.030972,0.01264,-0.027064,0.039282,0.087808,-0.009407,...,-0.022168,-0.011421,-0.005737,0.006808,-0.046234,-0.037241,-0.002679,0.02647,0.013321,-0.018136
2,0.067838,-0.045664,-0.009472,0.022142,0.025282,-0.002285,-0.01395,0.016893,0.067628,-0.01616,...,-0.004645,-0.030614,0.012686,-0.010691,-0.046417,-0.055645,-0.005022,0.024812,0.024613,-0.024027
3,0.046614,-0.027934,0.001222,0.002353,0.035407,-0.01243,-0.019765,-0.004876,0.046218,0.013925,...,-0.026521,-0.035216,-0.004109,-0.036879,-0.054527,-0.055834,0.017216,0.034123,0.002857,-0.03616
4,0.027034,0.003679,-0.008403,-0.007148,0.055771,0.004273,-0.059153,0.023611,0.039216,-0.014392,...,-0.006632,-0.00261,0.018518,-0.000571,-0.079509,-0.066124,0.009812,0.053018,-0.001678,-0.014339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.028561,-0.016232,-0.009719,-0.013754,0.055986,0.012621,-0.054065,0.004546,0.051606,-0.048284,...,0.013739,-0.013841,0.004438,-0.006116,-0.037663,-0.038199,-0.019396,0.066899,0.033964,-0.009207
196,0.065215,-0.046136,-0.031,0.012922,0.01391,-0.004673,-0.022419,0.004481,0.053905,-0.005379,...,-0.028995,-0.028779,-0.014075,0.012905,-0.041743,-0.049826,0.024213,0.030823,0.023324,-0.019394
197,0.070714,-0.000774,-0.007907,0.01583,0.035356,0.014577,-0.027239,0.005405,0.03067,-0.03415,...,0.000425,-0.022,-0.003267,-0.006078,-0.04284,-0.044118,0.009705,0.026114,0.036135,-0.020418
198,0.062252,0.00901,-0.027641,0.024176,0.013342,0.008863,-0.052536,0.010792,0.106955,0.001693,...,0.012361,0.011488,0.031775,0.00005,-0.048654,-0.045817,-0.02557,0.028476,0.032053,-0.024367
199,0.009476,-0.064125,-0.010046,0.008758,0.053316,0.007156,-0.074781,0.027832,-0.004232,-0.005932,...,-0.02368,-0.051384,-0.004355,-0.024937,-0.031182,-0.064692,0.005729,0.017431,0.008717,-0.016687

In [74]:
data=pd.concat([x_train,y_train],axis=1)

In [75]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
0,0.08059,0.003355,-0.021159,0.016135,0.011212,0.00094,-0.001987,0.008926,0.044516,-0.03038,...,0.005829,-0.000782,0.009129,-0.061586,-0.102544,0.013484,0.031701,0.023892,-0.040797,1
1,0.064557,-0.071604,-0.01181,0.012967,0.030972,0.01264,-0.027064,0.039282,0.087808,-0.009407,...,-0.011421,-0.005737,0.006808,-0.046234,-0.037241,-0.002679,0.02647,0.013321,-0.018136,0
2,0.067838,-0.045664,-0.009472,0.022142,0.025282,-0.002285,-0.01395,0.016893,0.067628,-0.01616,...,-0.030614,0.012686,-0.010691,-0.046417,-0.055645,-0.005022,0.024812,0.024613,-0.024027,1
3,0.046614,-0.027934,0.001222,0.002353,0.035407,-0.01243,-0.019765,-0.004876,0.046218,0.013925,...,-0.035216,-0.004109,-0.036879,-0.054527,-0.055834,0.017216,0.034123,0.002857,-0.03616,0
4,0.027034,0.003679,-0.008403,-0.007148,0.055771,0.004273,-0.059153,0.023611,0.039216,-0.014392,...,-0.00261,0.018518,-0.000571,-0.079509,-0.066124,0.009812,0.053018,-0.001678,-0.014339,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.028561,-0.016232,-0.009719,-0.013754,0.055986,0.012621,-0.054065,0.004546,0.051606,-0.048284,...,-0.013841,0.004438,-0.006116,-0.037663,-0.038199,-0.019396,0.066899,0.033964,-0.009207,1
196,0.065215,-0.046136,-0.031,0.012922,0.01391,-0.004673,-0.022419,0.004481,0.053905,-0.005379,...,-0.028779,-0.014075,0.012905,-0.041743,-0.049826,0.024213,0.030823,0.023324,-0.019394,1
197,0.070714,-0.000774,-0.007907,0.01583,0.035356,0.014577,-0.027239,0.005405,0.03067,-0.03415,...,-0.022,-0.003267,-0.006078,-0.04284,-0.044118,0.009705,0.026114,0.036135,-0.020418,1
198,0.062252,0.00901,-0.027641,0.024176,0.013342,0.008863,-0.052536,0.010792,0.106955,0.001693,...,0.011488,0.031775,0.00005,-0.048654,-0.045817,-0.02557,0.028476,0.032053,-0.024367,1
199,0.009476,-0.064125,-0.010046,0.008758,0.053316,0.007156,-0.074781,0.027832,-0.004232,-0.005932,...,-0.051384,-0.004355,-0.024937,-0.031182,-0.064692,0.005729,0.017431,0.008717,-0.016687,1

In [76]:
data=data.sample(frac=1)

In [77]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
140,0.065202,-0.02193,-0.013765,0.043635,0.025236,-0.021803,-0.064807,0.001926,0.045496,-0.037204,...,-0.007033,0.035963,0.023836,-0.034172,-0.053364,-0.022163,0.034611,-0.008505,-0.013458,1
118,0.065812,-0.043003,-0.003137,0.018701,0.028321,0.001513,-0.004523,0.028415,0.06889,0.012033,...,-0.007571,-0.032866,0.006187,-0.046164,-0.015931,0.006575,0.057757,-0.008774,-0.048536,0
132,0.075458,-0.035949,-0.008838,0.019019,0.020219,-0.005516,-0.046199,0.032549,0.080129,-0.036457,...,-0.01656,0.020998,0.00642,-0.037166,-0.050957,0.000001,0.037645,0.004172,-0.012593,1
154,0.038554,0.006394,-0.019581,0.044665,0.045806,0.00409,-0.04924,0.034611,0.069679,0.031101,...,0.027732,0.066009,-0.017395,-0.072192,-0.043114,-0.022482,0.028951,0.023175,-0.049398,0
78,0.096795,-0.031594,-0.006228,0.021152,0.032861,0.00886,-0.011512,-0.023627,0.017814,-0.043235,...,-0.013958,-0.029379,-0.004068,-0.054528,-0.057341,0.010587,0.042071,0.028165,-0.028556,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,0.041925,-0.001906,-0.04502,0.018539,0.018318,-0.01154,-0.031136,0.020285,0.010771,0.001111,...,-0.018115,-0.040911,0.006316,-0.01558,-0.014891,0.028904,0.013674,0.008483,-0.030174,1
90,0.002136,-0.051179,-0.025312,-0.007082,-0.001151,-0.01282,0.036942,-0.02415,-0.005955,-0.008161,...,-0.003717,0.003604,0.000874,-0.041359,-0.019463,0.020188,0.031194,-0.033213,-0.036158,1
151,0.011548,-0.0544,-0.013881,0.007228,0.069923,0.000365,-0.046878,0.022131,0.028447,-0.008709,...,-0.03881,-0.005631,-0.001699,-0.026767,-0.05306,0.004481,0.02807,-0.011101,-0.023499,1
95,-0.006014,-0.092013,-0.010577,0.021883,0.068056,-0.001443,-0.036181,0.027392,-0.015159,0.01328,...,-0.033243,-0.019912,-0.00041,-0.013316,-0.007418,0.00228,0.013026,-0.053885,-0.027355,1
186,0.064513,0.003531,-0.032436,0.003298,0.004245,0.012064,-0.011867,-0.014266,0.023826,-0.017319,...,-0.013701,-0.032349,0.004869,-0.044776,-0.045668,0.02109,0.029352,0.016109,-0.032615,1

In [78]:
data.to_csv("process2 test data after nlp(base).csv")