In [2]:
import pandas as pd

data_row=pd.read_csv('/Users/withmocha/Desktop/VisualStudioCode/Capstone Design project/Data/normal/preson conversation sentence. data.csv')

In [3]:
data_row

,Unnamed: 0,사람문장1,사람문장2,사람문장3
0,0,일은 왜 해도 해도 끝이 없을까? 화가 난다.,그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.,NaN
1,1,이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.,최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.,NaN
2,2,회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...,잘 안 맞는 사람이랑 억지로 잘 지내는 것보단 조금은 거리를 두고 예의를 갖춰서 대...,NaN
3,3,직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...,직장 사람들과 솔직하게 이야기해보고 싶어. 일하는 데에 방해된다고.,NaN
4,4,얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.,상사인 나에게 먼저 인사하지 않아서 매일 내가 먼저 인사한다고!,NaN
...,...,...,...,...
51625,51625,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고.,아무것도 할 수 없는 내가 무가치하게 느껴지고 실망스러워.,노년층을 위한 경제적 지원이나 부업 같은 것도 알아보아야겠어.
51626,51626,몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나.,마음 같아서는 다 할 수 있는 일인데 이젠 몸이 안 따라와 주니 화만 나.,남편과 함께 게이트볼이나 치러 가야겠어. 그럼 기분이 나아질 것 같아.
51627,51627,이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼.,주변 사람들은 다 노후 준비도 잘해두었던데 난 어떻게 해야 할지 모르겠어. 막막하기...,남편과 함께 실버 일자리나 노년층을 위한 국가 지원에 대해 자세히 알아보아야겠어.
51628,51628,몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가 나.,이제 할 수 있는 일도 없고 이렇게 힘들게 사는 게 불만스럽기만 해.,함께 친하게 지내던 동네 언니 동생들과 빈자리를 조금이나마 채울까 해.
51629,51629,남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라져.,사람들을 만나는 것이 어려워. 자꾸 사람들을 의심하게만 되고 말이야.,사람들을 볼 때 의심하고 불신하는 마음을 억눌러야겠어. 사람들을 색안경을 끼고 보지...

In [5]:
data_row.drop(columns=['Unnamed: 0'],inplace=True)

In [6]:
data_row

,사람문장1,사람문장2,사람문장3
0,일은 왜 해도 해도 끝이 없을까? 화가 난다.,그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.,NaN
1,이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.,최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.,NaN
2,회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...,잘 안 맞는 사람이랑 억지로 잘 지내는 것보단 조금은 거리를 두고 예의를 갖춰서 대...,NaN
3,직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...,직장 사람들과 솔직하게 이야기해보고 싶어. 일하는 데에 방해된다고.,NaN
4,얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.,상사인 나에게 먼저 인사하지 않아서 매일 내가 먼저 인사한다고!,NaN
...,...,...,...
51625,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고.,아무것도 할 수 없는 내가 무가치하게 느껴지고 실망스러워.,노년층을 위한 경제적 지원이나 부업 같은 것도 알아보아야겠어.
51626,몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나.,마음 같아서는 다 할 수 있는 일인데 이젠 몸이 안 따라와 주니 화만 나.,남편과 함께 게이트볼이나 치러 가야겠어. 그럼 기분이 나아질 것 같아.
51627,이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼.,주변 사람들은 다 노후 준비도 잘해두었던데 난 어떻게 해야 할지 모르겠어. 막막하기...,남편과 함께 실버 일자리나 노년층을 위한 국가 지원에 대해 자세히 알아보아야겠어.
51628,몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가 나.,이제 할 수 있는 일도 없고 이렇게 힘들게 사는 게 불만스럽기만 해.,함께 친하게 지내던 동네 언니 동생들과 빈자리를 조금이나마 채울까 해.
51629,남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라져.,사람들을 만나는 것이 어려워. 자꾸 사람들을 의심하게만 되고 말이야.,사람들을 볼 때 의심하고 불신하는 마음을 억눌러야겠어. 사람들을 색안경을 끼고 보지...

In [8]:
data_row.isnull().sum()

사람문장1       0
사람문장2       0
사람문장3    8935
dtype: int64

In [10]:
data_row.dtypes

사람문장1    object
사람문장2    object
사람문장3    object
dtype: object

In [13]:
data_x=data_row.drop(columns=['사람문장3'])

In [14]:
data_x

,사람문장1,사람문장2
0,일은 왜 해도 해도 끝이 없을까? 화가 난다.,그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.
1,이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.,최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.
2,회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...,잘 안 맞는 사람이랑 억지로 잘 지내는 것보단 조금은 거리를 두고 예의를 갖춰서 대...
3,직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...,직장 사람들과 솔직하게 이야기해보고 싶어. 일하는 데에 방해된다고.
4,얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.,상사인 나에게 먼저 인사하지 않아서 매일 내가 먼저 인사한다고!
...,...,...
51625,나이가 먹고 이제 돈도 못 벌어 오니까 어떻게 살아가야 할지 막막해. 능력도 없고.,아무것도 할 수 없는 내가 무가치하게 느껴지고 실망스러워.
51626,몸이 많이 약해졌나 봐. 이제 전과 같이 일하지 못할 것 같아 너무 짜증 나.,마음 같아서는 다 할 수 있는 일인데 이젠 몸이 안 따라와 주니 화만 나.
51627,이제 어떻게 해야 할지 모르겠어. 남편도 그렇고 노후 준비도 안 되어서 미래가 걱정돼.,주변 사람들은 다 노후 준비도 잘해두었던데 난 어떻게 해야 할지 모르겠어. 막막하기...
51628,몇십 년을 함께 살았던 남편과 이혼했어. 그동안의 세월에 배신감을 느끼고 너무 화가 나.,이제 할 수 있는 일도 없고 이렇게 힘들게 사는 게 불만스럽기만 해.
51629,남편과 결혼한 지 사십 년이야. 이제 사람 만나는 것도 버겁고 알던 사람도 점점 사라져.,사람들을 만나는 것이 어려워. 자꾸 사람들을 의심하게만 되고 말이야.

In [15]:
import konlpy

In [16]:
from konlpy.tag import Mecab

In [17]:
nlp_model = Mecab()

In [28]:
for i in range(100):
    print(f"문장 명사 추출 : {nlp_model.nouns(data_x.iloc[i,0])}")

문장 명사 추출 : ['일', '끝', '화']
문장 명사 추출 : ['이번', '달', '급여', '물가', '월급', '화', '나']
문장 명사 추출 : ['회사', '신입', '말투', '애', '생각', '스트레스']
문장 명사 추출 : ['직장', '막내', '이유', '나', '심부름', '일', '데']
문장 명사 추출 : ['얼마', '전', '입사', '신입', '사원', '나', '무시', '것', '화', '나']
문장 명사 추출 : ['직장', '시간', '거', '진로', '고민']
문장 명사 추출 : ['성인', '진로', '부모', '나']
문장 명사 추출 : ['퇴사', '지', '얼마', '직장']
문장 명사 추출 : ['졸업반', '취업', '생각']
문장 명사 추출 : ['요즘', '직장', '생활', '것']
문장 명사 추출 : ['취업', '나이', '취업']
문장 명사 추출 : ['면접', '부모', '직업', '질문']
문장 명사 추출 : ['큰일', '부장', '결재', '서류', '시간', '뒤', '제출', '어디']
문장 명사 추출 : ['나', '얼마', '전', '면접', '회사', '면접', '합격', '연락', '입사', '취소', '통보', '당혹']
문장 명사 추출 : ['길', '동네', '아주머니', '취업', '당황']
문장 명사 추출 : ['합격', '통보', '회사', '문자', '발송', '연락', '당혹']
문장 명사 추출 : ['나', '출근', '당황']
문장 명사 추출 : ['이번', '직장', '이직', '사람', '당황']
문장 명사 추출 : ['코로나', '때문', '뭘', '수', '취직', '준비', '시험', '취소', '말', '마비', '말', '때', '것']
문장 명사 추출 : ['회사', '실수', '것']
문장 명사 추출 : ['취업', '관련', '온몸', '마비', '것']
문장 명사 추출 : ['제도', '야근', '오늘', '야근']
문장 명사 추출 : ['우리', '회사', '사내', '분위기']
문장 명사 추출 : ['내', '회사', '직장', '생각']
문장 명사 추출 : ['회사', '전공', '시험', '시험', '결과']
문장 명사 추출 : ['면접', '관', '면접', '일', '연봉', '실수', '령', '액', '차이']
문장 명사 추출 : ['지인', '취업', '사기', '배신감']
문장 명사 추출 : ['우리', '부모', '나', '거', '내', '진로', '걱정', '때', '나', '걱정']
문장 명사 추출 : ['취업', '기분']
문장 명사 추출 : ['이번', '중소기업', '취업', '친구', '말']
문장 명사 추출 : ['저번', '주', '친구', '회사', '면접', '나']
문장 명사 추출 : ['요즘', '청년', '실업', '거', '취업', '기업', '채용']
문장 명사 추출 : ['직장', '일', '화', '나']
문장 명사 추출 : ['엄마', '진로', '문제', '화', '나']
문장 명사 추출 : ['면접']
문장 명사 추출 : ['부모', '취업', '잔소리', '나', '잔소리', '화', '나']
문장 명사 추출 : ['주변', '친구', '하나', '둘', '취업', '성공', '나', '불안', '나', '것', '걱정']
문장 명사 추출 : ['나', '내', '꿈', '무엇', '불안']
문장 명사 추출 : ['코로나', '때문', '출근', '것', '불안']
문장 명사 추출 : ['내년', '졸업', '취업', '문제', '때문', '걱정']
문장 명사 추출 : ['직장', '생활', '육', '개월', '차인데', '적응', '사회생활', '일', '줄']
문장 명사 추출 : ['이번', '면접', '비통', '마음']
문장 명사 추출 : ['나', '우울', '회사', '실수']
문장 명사 추출 : ['직장', '일', '스트레스', '신입', '직원', '일', '처리', '내', '일', '마무리', '게']
문장 명사 추출 : ['내', '업무', '일', '사수가', '성가']
문장 명사 추출 : ['회사', '동료', '나', '뭔가']
문장 명사 추출 : ['일']
문장 명사 추출 : ['일', '나']
문장 명사 추출 : ['우리', '신입', '오늘', '법']
문장 명사 추출 : ['실습생', '하나', '담당', '기간', '신경']
문장 명사 추출 : ['난', '언제', '직장', '수']
문장 명사 추출 : ['취업', '요즘', '구직', '자리']
문장 명사 추출 : ['취업', '시장', '직장', '것']
문장 명사 추출 : ['회사', '해고']
문장 명사 추출 : ['직장', '분', '퇴사']
문장 명사 추출 : ['진로', '문제', '때문', '고민']
문장 명사 추출 : ['고객', '나', '폭언', '때', '자존']
문장 명사 추출 : ['올해', '진급', '예정', '진급']
문장 명사 추출 : ['이번', '취업', '면접', '것']
문장 명사 추출 : ['코로나', '바이러스', '때문', '회사', '해고']
문장 명사 추출 : ['입사', '면접']
문장 명사 추출 : ['회사', '나', '신뢰', '것', '그건', '기분']
문장 명사 추출 : ['취업', '선배', '면접', '비결', '면접']
문장 명사 추출 : ['직장', '상사', '칭찬', '신']
문장 명사 추출 : ['취업', '신']
문장 명사 추출 : ['사장', '칭찬']
문장 명사 추출 : ['지난주', '회사', '원서', '접수', '합격']
문장 명사 추출 : ['얼마', '전', '면접', '실망', '마음']
문장 명사 추출 : ['이번', '면접', '실패', '언제', '취직', '수']
문장 명사 추출 : ['취업', '회사', '처음']
문장 명사 추출 : ['날', '면접', '회사', '물건', '사지', '거', '화', '나']
문장 명사 추출 : ['직장', '여성', '직원', '이유', '연봉']
문장 명사 추출 : ['나', '때', '가지', '분야', '진로', '설정', '지금', '분야', '직장', '취업', '노력']
문장 명사 추출 : ['회사', '따돌림', '것', '뭔가', '업무', '분담', '악의']
문장 명사 추출 : ['취업', '회사', '사원', '모집', '공고', '마음']
문장 명사 추출 : ['취업']
문장 명사 추출 : ['면접', '결과', '연락', '초조']
문장 명사 추출 : ['나', '원', '회사', '취업']
문장 명사 추출 : ['나', '상사', '게', '뭐', '거', '그게', '말']
문장 명사 추출 : ['내', '친구', '이번', '나', '회사', '취직', '학교', '때', '내', '공부', '열등']
문장 명사 추출 : ['취업', '준비', '중', '우울']
문장 명사 추출 : ['대학', '졸업', '후', '공무원', '시험', '준비', '오', '년']
문장 명사 추출 : ['이력서', '곳', '연락', '곳', '나', '운도', '복']
문장 명사 추출 : ['요새', '회사', '끝', '피곤', '친구', '휴대', '전화', '거']
문장 명사 추출 : ['취업', '코로나', '때문']
문장 명사 추출 : ['친구', '사업', '투자', '파업', '연락']
문장 명사 추출 : ['가족', '남', '말']
문장 명사 추출 : ['마음', '취업', '준비', '중', '힘']
문장 명사 추출 : ['일', '동기', '일', '처리', '이상', '내', '욕', '화', '나']
문장 명사 추출 : ['일', '사람', '나', '때문', '사과', '사이']
문장 명사 추출 : ['걱정', '평생', '연애', '결혼', '거']
문장 명사 추출 : ['결혼', '친구', '중', '친구', '나']
문장 명사 추출 : ['졸업', '얼마', '취업', '앞']
문장 명사 추출 : ['보육', '교사', '직업', '것', '우울']
문장 명사 추출 : ['결혼', '삼', '년', '차인데', '아내', '잔소리', '내', '아내', '것', '엄마', '것', '내', '물건', '것', '하나', '만', '사', '난리']
문장 명사 추출 : ['결혼', '준비', '행복', '날짜', '초조', '불안']
문장 명사 추출 : ['결혼', '코앞', '확신', '내']
문장 명사 추출 : ['결혼', '아이', '줄', '건', '아무것']
문장 명사 추출 : ['결혼', '친구', '비교']
문장 명사 추출 : ['나', '네이버', '인턴', '면접', '내', '것']

In [33]:
data=pd.DataFrame(index=range(0,data_row.shape[0]),columns=['word1','word2'])

In [68]:

A=nlp_model.nouns(data_x.iloc[1,0])

In [88]:
data.iloc[1,0]=nlp_model.nouns(data_x.iloc[1,0])
print(data.iloc[1,0])

['이번', '달', '급여', '물가', '월급', '화', '나']

In [90]:
data

                           word1 word2
0                            NaN   NaN
1      [이번, 달, 급여, 물가, 월급, 화, 나]   NaN
2                            NaN   NaN
3                            NaN   NaN
4                            NaN   NaN
...                          ...   ...
51625                        NaN   NaN
51626                        NaN   NaN
51627                        NaN   NaN
51628                        NaN   NaN
51629                        NaN   NaN

[51630 rows x 2 columns]

In [92]:
for i in range(data_x.shape[0]):
        A=nlp_model.nouns(data_x.iloc[i,0])
        data.iloc[i][0]=A

/var/folders/gb/hslcbzfs0bvcnj3zxtfrxt_r0000gn/T/ipykernel_74309/1780325728.py:3: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  data.iloc[i][0]=A

In [93]:
data

                                     word1 word2
0                                [일, 끝, 화]   NaN
1                [이번, 달, 급여, 물가, 월급, 화, 나]   NaN
2                [회사, 신입, 말투, 애, 생각, 스트레스]   NaN
3               [직장, 막내, 이유, 나, 심부름, 일, 데]   NaN
4      [얼마, 전, 입사, 신입, 사원, 나, 무시, 것, 화, 나]   NaN
...                                    ...   ...
51625                          [나이, 돈, 능력]   NaN
51626                     [몸, 전, 일, 것, 짜증]   NaN
51627                 [남편, 노후, 준비, 미래, 걱정]   NaN
51628    [십, 년, 남편, 이혼, 동안, 세월, 배신감, 화, 나]   NaN
51629      [남편, 결혼, 지, 사, 십, 년, 사람, 것, 사람]   NaN

[51630 rows x 2 columns]

In [95]:
for i in range(data_x.shape[0]):
        A=nlp_model.nouns(data_x.iloc[i,1])
        data.iloc[i,1]=A

In [96]:
data

                                     word1                            word2
0                        [내, 해결, 게, 남, 부담]                [내, 해결, 게, 남, 부담]
1                [이번, 달, 급여, 물가, 월급, 화, 나]  [최대한, 지출, 억제, 월급, 고정, 지출, 수, 것]
2                [회사, 신입, 말투, 애, 생각, 스트레스]      [사람, 것, 거리, 예의, 게, 스트레스, 것]
3               [직장, 막내, 이유, 나, 심부름, 일, 데]          [직장, 사람, 이야기, 일, 데, 방해]
4      [얼마, 전, 입사, 신입, 사원, 나, 무시, 것, 화, 나]               [상사, 나, 인사, 내, 인사]
...                                    ...                              ...
51625                          [나이, 돈, 능력]              [아무것, 수, 내, 가치, 실망]
51626                     [몸, 전, 일, 것, 짜증]            [마음, 수, 일, 이젠, 몸, 주니]
51627                 [남편, 노후, 준비, 미래, 걱정]              [주변, 사람, 노후, 준비, 난]
51628    [십, 년, 남편, 이혼, 동안, 세월, 배신감, 화, 나]                    [수, 일, 게, 불만]
51629      [남편, 결혼, 지, 사, 십, 년, 사람, 것, 사람]               [사람, 것, 사람, 의심, 말]

[51630 rows x 2 columns]

In [97]:
data.to_csv('word data.csv')