In [1]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0521(final)/data/process/process2/process2 test data row.csv",index_col=0)

In [2]:
data_row

                                               sentence  predict
1385       아 네 예 알겠습니다. 조금만 기다려 전화는 호주머니에 넣고 이동하시겠습니다 네        1
646    어디에 상환하신거... 수요일에 상환하신..아닌데 잠시만요 목요일날 상환하신거 말...        0
423    서울 중앙 지검 검찰청이요. 그 중앙 하단 쪽에 보이면 그 파란색 박스 안에 나의...        1
377    위임 처리하시면 당일로도 가능하시고 위임을 하면 어떻게 되요? 위임하실 경우에는 ...        0
482    예 말씀 드리는 거 말씀 드리는데 집중을 안 하시는 거 같다고요 아 예 집중하실 ...        0
...                                                 ...      ...
632     저희가 인제 조사 내용을 녹취를 할 건데요  저 아까 어디소속 누구라고 말씀하셨...        1
853                             잠깐만 갑자기 생각이 안 나네.  요? 예        0
1291                                       김기훈 예 명의도요 예        1
393    그러시고 다른 계좌 건. 다른 것도 다 제가 한거에요. 다른 계좌건 어떤 계좌건 ...        1
1496   그때 제가 절차 다 질문 드리면 본인께서는 아시는 대로 진술을 해주시면 되는겁니다...        1

[200 rows x 2 columns]

In [3]:
data_row.isnull().sum()

sentence    0
predict     0
dtype: int64

In [4]:
data=data_row.sample(frac=1)

In [5]:
data

                                               sentence  predict
1095   네 일단 지금 김기훈을 통해서 이번 사건 연루되신 분이 총 전국에 290 여명이 ...        1
133     네 납부가 완료 되셨잖아요 그럼 그쪽 전산망으로 이제 고객센터한테 보내야 돼요 서류를        0
1385       아 네 예 알겠습니다. 조금만 기다려 전화는 호주머니에 넣고 이동하시겠습니다 네        1
807    네네 어디어디 이용중이십니까? 너무 많아가지고  네 대부업건 어디어디 이용중이세요...        0
1287              아이디로다가 추가하면 나는 들어가실 게요 네 예 예 준비되셨나요 네        1
...                                                 ...      ...
913             자 본인... 저 지금 현대백화점까지 왔어요. 어디? 현대 백화점이요.        1
1116   중도 상환 수수료 안 받습니다. 없습니다. 아 그럼 그때 한 번 방문을 해주실래요...        0
1226   문자 본인 앞으로 나와있는 정보 확인하시고요. 아 지워져 쓰면은 네 네 지웠어요 ...        1
68     아 그러니까 사장님께서 그 안쓰시는 통장 있으시면 400에서 450까지 선지급 해...        0
1048   가가지고 시간 또 걸리고 그렇죠? 그거는 뭐 고객님께서 결정을 해주셔야죠. 저희가...        0

[200 rows x 2 columns]

In [6]:
data.to_csv("process2 test data before nlp(jhgan).csv")

In [7]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('jhgan/ko-sbert-sts')

In [8]:
data.isnull().sum()

sentence    0
predict     0
dtype: int64

In [9]:
A=model.encode(data.iloc[0,0])

In [10]:
A.shape[0]

768

In [11]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [12]:
x_train=pd.DataFrame(index=range(0,data.shape[0]),columns=list)

In [13]:
x_train.shape

(200, 768)

In [14]:

y_train=pd.DataFrame(index=range(0,x_train.shape[0]),columns=['predict'])

In [15]:

x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
y_train

    predict
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
..      ...
195     NaN
196     NaN
197     NaN
198     NaN
199     NaN

[200 rows x 1 columns]

In [17]:
for i in range(data.shape[0]):
    y_train.iloc[i,0]=data.iloc[i,1]

In [18]:
y_train

    predict
0         1
1         0
2         1
3         0
4         1
..      ...
195       1
196       0
197       1
198       0
199       0

[200 rows x 1 columns]

In [19]:
y_train.isnull().sum()

predict    0
dtype: int64

In [20]:
for i in range(data.shape[0]):
    vector=[]
    vector=model.encode(data.iloc[i,0])
    for j in range(x_train.shape[1]):
        x_train.iloc[i,j]=vector[j]

In [21]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.043137,0.411971,0.769539,-0.063136,-0.362503,0.226766,0.028324,-0.338095,-0.18618,-0.290538,...,-0.244187,0.767648,0.133714,0.740406,0.188326,0.062721,1.092162,-0.194607,-0.587033,1.281143
1,0.827956,1.412218,-0.139616,0.838201,-1.385238,-0.214196,0.417318,0.689768,0.937995,0.228385,...,0.515517,1.118405,0.308931,-0.24042,-0.664819,0.094184,0.522866,0.415247,0.788634,1.516763
2,-0.935004,0.886285,0.734498,0.367486,-1.339458,0.294112,-0.466026,0.292115,0.45972,-0.143753,...,-0.065815,0.775351,0.096598,0.791253,-0.129383,-0.244089,-0.716399,-0.373267,-0.740642,1.619547
3,0.881403,0.359288,0.11733,0.50906,-1.162144,-0.182536,0.170413,0.615523,-0.471238,-1.639416,...,-0.15371,0.915108,1.01477,0.485792,-0.477127,-0.246234,0.436716,0.178753,-1.04418,0.446452
4,-0.685643,-0.216709,-0.210524,0.750113,-0.933977,0.303367,0.095667,-0.397742,-0.259917,-0.305356,...,0.704395,0.515776,0.031469,0.695998,-0.047221,-0.5745,0.842272,-0.418089,0.167234,1.65145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-0.197837,0.190503,-0.224905,0.411148,-0.766492,-0.571186,0.185318,0.602921,1.141759,-0.877209,...,-0.444405,-0.14382,-0.289383,-0.48225,-0.323818,0.428182,0.633131,0.645501,-0.369077,1.617245
196,0.126114,0.23103,-0.439494,0.035482,-0.874836,-0.763867,-0.839338,0.274254,-0.428093,-0.136528,...,-0.507543,0.130349,0.921969,0.659512,0.129187,-0.524295,0.186403,-0.344377,-0.041126,0.389495
197,-0.046751,0.567345,0.230473,0.776183,-1.190358,0.463584,0.094376,0.862457,-0.298319,-0.050125,...,-0.227399,1.291288,0.737915,0.126911,-0.173137,-0.514815,0.104725,-0.676185,-0.773574,1.294171
198,0.387215,0.472943,-0.232069,0.647047,-0.508633,-0.242634,0.46054,0.532094,-0.356595,-1.280555,...,0.13631,0.690715,0.480925,0.164426,-0.08225,0.342949,0.534682,-0.503734,-0.79604,0.750542
199,0.433216,-0.304954,-0.130597,0.508261,-0.142092,-0.935209,-0.293055,-0.300528,-0.26784,0.762948,...,0.410378,0.118742,0.333059,-0.293514,-0.302139,-0.709087,-0.412794,0.00468,-0.537127,0.544389

In [22]:
data=pd.concat([x_train,y_train],axis=1)

In [23]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
0,0.043137,0.411971,0.769539,-0.063136,-0.362503,0.226766,0.028324,-0.338095,-0.18618,-0.290538,...,0.767648,0.133714,0.740406,0.188326,0.062721,1.092162,-0.194607,-0.587033,1.281143,1
1,0.827956,1.412218,-0.139616,0.838201,-1.385238,-0.214196,0.417318,0.689768,0.937995,0.228385,...,1.118405,0.308931,-0.24042,-0.664819,0.094184,0.522866,0.415247,0.788634,1.516763,0
2,-0.935004,0.886285,0.734498,0.367486,-1.339458,0.294112,-0.466026,0.292115,0.45972,-0.143753,...,0.775351,0.096598,0.791253,-0.129383,-0.244089,-0.716399,-0.373267,-0.740642,1.619547,1
3,0.881403,0.359288,0.11733,0.50906,-1.162144,-0.182536,0.170413,0.615523,-0.471238,-1.639416,...,0.915108,1.01477,0.485792,-0.477127,-0.246234,0.436716,0.178753,-1.04418,0.446452,0
4,-0.685643,-0.216709,-0.210524,0.750113,-0.933977,0.303367,0.095667,-0.397742,-0.259917,-0.305356,...,0.515776,0.031469,0.695998,-0.047221,-0.5745,0.842272,-0.418089,0.167234,1.65145,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-0.197837,0.190503,-0.224905,0.411148,-0.766492,-0.571186,0.185318,0.602921,1.141759,-0.877209,...,-0.14382,-0.289383,-0.48225,-0.323818,0.428182,0.633131,0.645501,-0.369077,1.617245,1
196,0.126114,0.23103,-0.439494,0.035482,-0.874836,-0.763867,-0.839338,0.274254,-0.428093,-0.136528,...,0.130349,0.921969,0.659512,0.129187,-0.524295,0.186403,-0.344377,-0.041126,0.389495,0
197,-0.046751,0.567345,0.230473,0.776183,-1.190358,0.463584,0.094376,0.862457,-0.298319,-0.050125,...,1.291288,0.737915,0.126911,-0.173137,-0.514815,0.104725,-0.676185,-0.773574,1.294171,1
198,0.387215,0.472943,-0.232069,0.647047,-0.508633,-0.242634,0.46054,0.532094,-0.356595,-1.280555,...,0.690715,0.480925,0.164426,-0.08225,0.342949,0.534682,-0.503734,-0.79604,0.750542,0
199,0.433216,-0.304954,-0.130597,0.508261,-0.142092,-0.935209,-0.293055,-0.300528,-0.26784,0.762948,...,0.118742,0.333059,-0.293514,-0.302139,-0.709087,-0.412794,0.00468,-0.537127,0.544389,0

In [24]:
data=data.sample(frac=1)

In [25]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
139,0.098854,-0.200154,0.011525,1.200743,-0.446034,-0.364514,0.792838,0.643257,0.05239,-0.82287,...,1.131698,0.556099,1.194595,-0.888124,0.583057,0.871201,0.560663,0.006678,0.507495,0
124,1.041939,-0.007202,-0.664063,0.575203,-1.060981,-0.541944,-0.944298,0.852507,0.01113,-0.458686,...,0.600565,0.743798,0.472484,-0.613371,-0.085184,0.680229,0.403734,-0.424941,0.948991,0
186,-0.297504,0.607902,-0.398278,0.593084,-0.988594,-0.512478,0.442438,0.302521,-0.176532,-0.319853,...,1.14196,0.442923,0.494472,-0.254827,-0.038248,0.841181,0.292593,0.902041,0.714166,1
64,0.033783,0.074899,0.206552,0.931511,-0.927608,-0.613031,-0.980561,0.678197,-0.455629,0.344488,...,0.969147,1.510712,1.161268,0.586537,-0.826994,0.65869,-0.880047,-0.163937,0.843778,1
160,-1.091896,-0.061436,-0.654971,0.848429,-0.708019,0.206895,-0.969523,1.390378,0.644847,0.815152,...,0.755004,0.665403,0.358428,-0.071692,0.177915,1.248073,-0.363391,0.334156,-0.099679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,-0.408902,0.128887,0.2068,-0.508353,-0.618417,-0.315056,0.564198,-0.553164,-0.401645,-0.928627,...,0.391983,0.940348,0.083009,0.37936,0.305596,0.140347,0.098354,0.373508,1.628349,0
193,1.591635,-0.438722,-0.427683,0.063869,-0.555203,-0.361926,0.100294,0.867302,0.42915,0.672329,...,0.81401,-0.007698,1.890839,0.153834,0.028449,1.118509,-0.519989,-1.237203,0.124539,1
123,0.769204,-0.37777,0.103542,0.761767,-1.328229,0.061825,0.94737,0.449142,0.179501,1.044475,...,1.412432,1.070225,0.479282,-0.899434,-0.858125,0.656913,-1.068868,-0.339046,0.750778,1
55,-0.787755,-0.480289,1.004402,0.3783,0.831319,-0.767652,-0.621379,0.763584,-0.182022,0.828586,...,0.494529,0.51482,-0.177284,-1.037336,-0.560356,0.396045,-0.286128,-0.087251,1.164255,0
112,0.935142,0.586119,0.341158,0.865516,-0.595837,0.397844,0.013294,0.256527,-0.940387,0.396471,...,0.656168,0.325871,0.575752,0.045523,0.305204,0.099084,-0.375604,-1.044596,1.135517,1

In [26]:
data.to_csv("process2 test data after nlp(jhgan).csv")