In [16]:
import pandas as pd

data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0518(final)/normal row/일반 민원(증강big).csv",index_col=0)
data_ab1=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0518(final)/abnormal row/대출 사기형 보이스피싱(증강big2).csv",index_col=0)
data_ab2=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0518(final)/abnormal row/기관 사칭형 보이스피싱(증강big2).csv",index_col=0)

In [17]:
data

                                                sentence  predict
0                   이용함하시각는 은행의 사이트에서 지방세 결제가 가능성 있음합니다.        0
1             그럼 스마트폰에서 기업은행 어플을 설치하시기면 납부하기가 할 수 있음합니다.        0
2                                      방문함납입도 할 수 있음합니다.        0
3                               도보로 10부분위치에 서울역지점이 있습니다.        0
4                                   도보로 가시는게 빠를 사항 같습니다.        0
...                                                  ...      ...
16926                       한 달소득 실수령액이 150그냥원화 이하여야합니다.        0
16927                            서울 지역소재 직장근무로 제한하고있습니다.        0
16928                                        62400돈 입니다.        0
16929                                     1423200금액 입니다.        0
16930  입주신청서와 추천서, 급여내역서 외 기타 서류를 갖고 웹사이트에서 가입 신청하면 됩니다.        0

[12382 rows x 2 columns]

In [18]:
data=data.sample(frac=1)

In [19]:
data_ab1

                                                sentence  predict
0       위임하실 경우에는 방문이나 내방 없이 드리는 전화 받으시고 통신 녹음를 통해서 대...        1
1       지금 다짜고짜 여쭤보면 어떡합니까? 고객님 식별증도 접수도 안 해줬는데 그냥 은행...        1
2       심사자료 정리를 바로 진행 진행 도와드리겠습니다. 실제 거주하시는 지역은 울산 남...        1
3       예 차후에 변동 안 되세요 예 대출 승인 나셨을 경우에 대출금 송금 받아 보실 수...        1
4       수납 담당자님 은행 은행 계정 숫자는 바로 카카오톡으로 보내드릴거구요. 수납 가능...        1
...                                                  ...      ...
10481   아휴 그럼 어떻게 해요. 제가 예금 바로 쓸 수가 있는거지. 느낌이 완전 보이스 ...        1
10482   돈을 먼저 넣으라는 거는 나는 좀 이해가 안되네요.여보세요 안녕하세요 고객님 김종...        1
10483     네 사기 행위 범죄 행위치지 마시고요 다른사람한테 피해주지 마시구요 그러다 벌받아요        1
10484   무슨소리하시는거죠? 지금 그 은행 계정 제가 신고 해놨거든요? 네 입출금 계정에 ...        1
10485   사장님께서 혹시 안쓰시는 은행 입출금 계좌가 있으시면 저희가 월 400에서 450...        1

[10486 rows x 2 columns]

In [20]:
data_ab2

                                                sentence  predict
0       위임하실 경우에는 방문이나 내방 없이 드리는 전화 받으시고 통신 녹음를 통해서 대...        1
1       지금 다짜고짜 여쭤보면 어떡합니까? 고객님 식별증도 접수도 안 해줬는데 그냥 은행...        1
2       심사자료 정리를 바로 진행 진행 도와드리겠습니다. 실제 거주하시는 지역은 울산 남...        1
3       예 차후에 변동 안 되세요 예 대출 승인 나셨을 경우에 대출금 송금 받아 보실 수...        1
4       수납 담당자님 은행 은행 계정 숫자는 바로 카카오톡으로 보내드릴거구요. 수납 가능...        1
...                                                  ...      ...
10481   아휴 그럼 어떻게 해요. 제가 예금 바로 쓸 수가 있는거지. 느낌이 완전 보이스 ...        1
10482   돈을 먼저 넣으라는 거는 나는 좀 이해가 안되네요.여보세요 안녕하세요 고객님 김종...        1
10483     네 사기 행위 범죄 행위치지 마시고요 다른사람한테 피해주지 마시구요 그러다 벌받아요        1
10484   무슨소리하시는거죠? 지금 그 은행 계정 제가 신고 해놨거든요? 네 입출금 계정에 ...        1
10485   사장님께서 혹시 안쓰시는 은행 입출금 계좌가 있으시면 저희가 월 400에서 450...        1

[10486 rows x 2 columns]

In [21]:
data_ab=pd.concat([data_ab1,data_ab2])

In [22]:
data_ab

                                                sentence  predict
0       위임하실 경우에는 방문이나 내방 없이 드리는 전화 받으시고 통신 녹음를 통해서 대...        1
1       지금 다짜고짜 여쭤보면 어떡합니까? 고객님 식별증도 접수도 안 해줬는데 그냥 은행...        1
2       심사자료 정리를 바로 진행 진행 도와드리겠습니다. 실제 거주하시는 지역은 울산 남...        1
3       예 차후에 변동 안 되세요 예 대출 승인 나셨을 경우에 대출금 송금 받아 보실 수...        1
4       수납 담당자님 은행 은행 계정 숫자는 바로 카카오톡으로 보내드릴거구요. 수납 가능...        1
...                                                  ...      ...
10481   아휴 그럼 어떻게 해요. 제가 예금 바로 쓸 수가 있는거지. 느낌이 완전 보이스 ...        1
10482   돈을 먼저 넣으라는 거는 나는 좀 이해가 안되네요.여보세요 안녕하세요 고객님 김종...        1
10483     네 사기 행위 범죄 행위치지 마시고요 다른사람한테 피해주지 마시구요 그러다 벌받아요        1
10484   무슨소리하시는거죠? 지금 그 은행 계정 제가 신고 해놨거든요? 네 입출금 계정에 ...        1
10485   사장님께서 혹시 안쓰시는 은행 입출금 계좌가 있으시면 저희가 월 400에서 450...        1

[20972 rows x 2 columns]

In [23]:
data=pd.concat([data,data_ab])

In [24]:
data

                                                sentence  predict
10259                        신분증 지참하시기고 내방접수도 할 수 있는합니다.        0
8457   반납한 자료의 당일 재 대출은 불가하며, 예약이 없다면 다음날부터 대출이 할 수 있...        0
5389                                인터넷 지급은 불할 수 있음합니다.         0
4431    각 공연마다 요금이 상이하니 홈페이지 주소에서 예약시각 확인하기하여 주시각기 바랍니다.        0
2339   귀농귀촌 희망 도시민 및 은퇴예정자의 안정적인 귀농귀촌 정착 보조을 위해 교육프로그...        0
...                                                  ...      ...
10481   아휴 그럼 어떻게 해요. 제가 예금 바로 쓸 수가 있는거지. 느낌이 완전 보이스 ...        1
10482   돈을 먼저 넣으라는 거는 나는 좀 이해가 안되네요.여보세요 안녕하세요 고객님 김종...        1
10483     네 사기 행위 범죄 행위치지 마시고요 다른사람한테 피해주지 마시구요 그러다 벌받아요        1
10484   무슨소리하시는거죠? 지금 그 은행 계정 제가 신고 해놨거든요? 네 입출금 계정에 ...        1
10485   사장님께서 혹시 안쓰시는 은행 입출금 계좌가 있으시면 저희가 월 400에서 450...        1

[33354 rows x 2 columns]

In [25]:
data=data.sample(frac=1)

In [26]:
data

                                               sentence  predict
4119   재정을 먼저 넣으라는 거는 나는 좀 이해가 안되네요.여보세요 안녕하세요 고객님 김...        1
500          현재 아드님이 수입이 있으셔서 민원자분께서 기초생활수급자에 해당됨이 안돼요.        0
2846                         경기도 지역 사회화페를 발행하기받으셔야 합니다.        0
5232   아휴 그럼 어떻게 해요. 제가 자금 돈 입금 바로 쓸 수가 있는거지. 느낌이 완전...        1
3206   재정을 먼저 넣으라는 거는 나는 좀 이해가 안되네요.여보세요 안녕하세요 고객님 김...        1
...                                                 ...      ...
63     느낌이 완전 보이스 보이스피싱 공격 이상한게 아니라 지금 자격 요건이 안 되시잖아...        1
4365                            진료비보조과 출산 축하금을 후원해드립니다.        0
7270   원래는 먼저 넣는 거 아니에요. 근데 위임처리하실 경우에만 먼저 받는 거예요 아 ...        1
7631   아휴 그럼 어떻게 해요. 제가 재정 돈 입금 바로 쓸 수가 있는거지. 느낌이 완전...        1
415                            네 주소 불러주시기면 바로 수정해드릴게요.         0

[33354 rows x 2 columns]

In [27]:
test_data=data[:3000]

In [28]:
train_data=data[3000:data.shape[0]]

In [29]:
train_data

                                               sentence  predict
9555   아 그렇게는 안되구요. 그러면은 저희가 이제 따로 수납 처리 안 받고 공증을 직접...        1
6665        네 사기 범죄 행위치지 마시고요 다른사람한테 피해주지 마시구요 그러다 벌받아요        1
7178   예 차후에 변동 안 되세요 예 대출 승인 나셨을 경우에 대출금 송금 받아 보실 수...        1
8716                         그럼 일단 상황을 지켜보셔야 될 사물 같습니다.        0
1266  개인신용이 현저히 나쁘거나 개인회생 절차 진행 가운데이면 은행에서 대출이 승인되지 ...        0
...                                                 ...      ...
63     느낌이 완전 보이스 보이스피싱 공격 이상한게 아니라 지금 자격 요건이 안 되시잖아...        1
4365                            진료비보조과 출산 축하금을 후원해드립니다.        0
7270   원래는 먼저 넣는 거 아니에요. 근데 위임처리하실 경우에만 먼저 받는 거예요 아 ...        1
7631   아휴 그럼 어떻게 해요. 제가 재정 돈 입금 바로 쓸 수가 있는거지. 느낌이 완전...        1
415                            네 주소 불러주시기면 바로 수정해드릴게요.         0

[30354 rows x 2 columns]

In [30]:
train_data.to_csv("train data(0520_2).csv")
test_data.to_csv("test data(0520_2).csv")