In [1]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/final/process1/trian/process 1 train data row.csv",index_col=0)

In [2]:
data_row

                                               sentence  predict
297   기간은 몇 년으로 되어있으신가요?대리수령시 신청인 신분증과 대리인신분증, 접수증 있...        0
2232  지역이 어디신가요?연말정산은 매년 2월에 실시합니다.출력사유가 어떻게 되시나요?올해...        0
685   올 해 지급기준이 몇프로인가요?네 가능해요. 이직할때 회사가 너무 멀리이사가서 그런...        0
1922   네  어떤것이 궁금한가요?신청하시면 4년간 유예 되십니다. 소상공인 이신가요?대출...        0
909   바꿔주실 수 있나요?7일 미만일 경우 만원입니다. 네 여보세요?네, 신고와 함께 즉...        0
...                                                 ...      ...
66     매 월 상환이 그렇죠? 원금 예 그럼 뭐 바로 해야겠네. 가가지고 시간 또 걸리고...        1
2124  절차가 궁금하십니까?입급은행을 '지방세입'으로 선택하고 고지서에 기재된 지방세입계좌...        0
1234   서울지검어디세요 첨단 범죄 수사 2부입니다 예? 첨단범죄수사 2부에 이경호요 이경...        1
212    아니에요. 유선상으로 대출할 때는 찾아가는 거는 최하위 우선 순위 실행입니다 음 ...        1
1063  언제부턴지 아시나요?네, 청년포털에서 정보 변경하실 수 있습니다. 크린넷시설같다는 ...        0

[3780 rows x 2 columns]

In [3]:
data_row.isnull().sum()

sentence    0
predict     0
dtype: int64

In [4]:
data=data_row.sample(frac=1)

In [5]:
data

                                               sentence  predict
1490  보유하고 계신 차종이 무엇인가요? 재산세는 지방세입니다.차종이 어떻게 되나요? 네,...        0
1910   네, 맞습니다. 어떤민원 도와드릴까요?연말정산은 매년 2월에 실시합니다. 다치신곳...        0
2082  예.어떤걸 도와 드릴까요?주택규모는 60제곱미터 이하나 전세 또는 보증부월세로 계약...        0
1012  네. 무엇을 도와드릴까요?네, 그렇습니다. 네. 무엇을 도와드릴까요?신용카드나, 체...        0
433    OOO씨. OOO씨. 여보세요? OOO씨. 진짜 사기 아니죠 이거. 진짜 금감원....        1
...                                                 ...      ...
1018  어떤 한강공원 주차장 이용 예정이신가요?감사합니다. 승용차이신가요?네, 발급 가능합...        0
680   네 무엇을 도와드릴까요?경찰서 방문하셔서 분실신고를 해주면 돼요.네 다른 궁금한 사...        0
680    이천 일십만. 일십만. 아니죠 일십삼만 일십삼만 이렇게 쓰세요. 일십삼만. 어 그...        1
391    엄청 오래 걸렸네요. 네 한 숨 나오죠? 어쩔수 없죠. 고생 많았어요. 자 일단은...        1
1027  네. 무엇을 도와드릴까요?주소지 변경 시 신규 발급 하셔야 합니다. 더 궁금하신 사...        0

[3780 rows x 2 columns]

In [6]:
data.to_csv("process1 train data before nlp(jhgan).csv")

In [7]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('jhgan/ko-sbert-sts')

In [8]:
data.isnull().sum()

sentence    0
predict     0
dtype: int64

In [9]:
A=model.encode(data.iloc[0,0])

In [10]:
A.shape[0]

768

In [11]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [12]:
x_train=pd.DataFrame(index=range(0,data.shape[0]),columns=list)

In [13]:
x_train.shape

(3780, 768)

In [14]:

y_train=pd.DataFrame(index=range(0,x_train.shape[0]),columns=['predict'])

In [15]:

x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3778,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3779,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
y_train

     predict
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
3775     NaN
3776     NaN
3777     NaN
3778     NaN
3779     NaN

[3780 rows x 1 columns]

In [17]:
for i in range(data.shape[0]):
    y_train.iloc[i,0]=data.iloc[i,1]

In [18]:
y_train

     predict
0          0
1          0
2          0
3          0
4          1
...      ...
3775       0
3776       0
3777       1
3778       1
3779       0

[3780 rows x 1 columns]

In [19]:
y_train.isnull().sum()

predict    0
dtype: int64

In [20]:
for i in range(data.shape[0]):
    vector=[]
    vector=model.encode(data.iloc[i,0])
    for j in range(x_train.shape[1]):
        x_train.iloc[i,j]=vector[j]

In [21]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.399335,0.212908,-1.079054,0.73835,-0.068925,-1.096343,0.24713,0.371202,0.381506,-0.61188,...,0.341849,0.743762,0.268085,0.060103,0.278702,-0.745044,1.098013,-0.084517,-0.041216,0.898431
1,0.573353,0.70867,-0.613382,1.238256,0.098393,-0.592201,0.083161,0.056328,0.569411,-0.800951,...,1.086236,0.442493,0.816005,1.014547,-0.098348,-0.221292,0.913813,0.217043,-0.498482,0.280956
2,-0.062676,0.44137,-0.191168,0.147124,-0.820729,-0.519271,0.071344,0.638939,-0.397044,-0.51072,...,-0.148534,0.159318,0.042403,0.580304,-0.001505,0.312235,0.100235,-0.393342,-0.752477,1.08827
3,0.827058,-0.155112,-0.341741,1.021212,-0.123689,-1.093875,-0.239992,0.85712,0.382692,-0.543145,...,0.509322,-0.61283,-0.061454,0.949677,-0.870268,-0.080207,0.530275,-0.180064,-1.244822,0.588587
4,0.947664,0.307353,0.088852,0.092378,0.300358,-0.858926,0.678646,0.125158,-0.648431,-0.453974,...,0.582548,0.540117,0.428879,1.575706,-1.416005,-0.738884,0.352613,0.235541,-0.540703,-0.706139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3775,0.596103,-0.123397,-0.138377,0.425166,-0.482111,-0.969241,-0.192715,0.58983,-0.130476,-0.999129,...,0.312976,0.249356,1.029132,-0.332343,0.007998,0.618219,0.658851,0.080547,-1.026872,0.831986
3776,0.537198,0.610258,-0.373453,0.538863,-0.747154,-0.166254,0.288404,0.294042,0.368194,-0.951905,...,-0.426539,-0.056026,0.422636,1.029145,-0.796317,0.423893,0.317059,0.876707,-0.588022,0.72427
3777,0.586338,-0.61004,-0.464729,0.43172,-0.105702,-0.824378,-0.02586,0.778583,-0.846392,0.096839,...,0.298372,0.248312,-0.153707,0.785722,0.598168,-0.390768,0.285832,-0.427053,-1.195046,0.259034
3778,0.427412,0.587215,-0.24888,0.233618,-0.722975,0.062959,0.574484,0.530069,0.023453,-0.02116,...,-0.296362,0.698019,0.59427,1.04469,0.244757,-0.623698,0.116014,0.038047,-0.73427,0.68405
3779,-0.001067,0.391166,-0.278283,0.789859,-0.309995,-1.201142,-0.379411,-0.028375,-0.169312,-0.530384,...,0.31027,0.677638,-0.366761,0.345031,-0.839798,-0.150583,0.696749,-0.265417,-0.80158,1.510754

In [22]:
data=pd.concat([x_train,y_train],axis=1)

In [23]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
0,0.399335,0.212908,-1.079054,0.73835,-0.068925,-1.096343,0.24713,0.371202,0.381506,-0.61188,...,0.743762,0.268085,0.060103,0.278702,-0.745044,1.098013,-0.084517,-0.041216,0.898431,0
1,0.573353,0.70867,-0.613382,1.238256,0.098393,-0.592201,0.083161,0.056328,0.569411,-0.800951,...,0.442493,0.816005,1.014547,-0.098348,-0.221292,0.913813,0.217043,-0.498482,0.280956,0
2,-0.062676,0.44137,-0.191168,0.147124,-0.820729,-0.519271,0.071344,0.638939,-0.397044,-0.51072,...,0.159318,0.042403,0.580304,-0.001505,0.312235,0.100235,-0.393342,-0.752477,1.08827,0
3,0.827058,-0.155112,-0.341741,1.021212,-0.123689,-1.093875,-0.239992,0.85712,0.382692,-0.543145,...,-0.61283,-0.061454,0.949677,-0.870268,-0.080207,0.530275,-0.180064,-1.244822,0.588587,0
4,0.947664,0.307353,0.088852,0.092378,0.300358,-0.858926,0.678646,0.125158,-0.648431,-0.453974,...,0.540117,0.428879,1.575706,-1.416005,-0.738884,0.352613,0.235541,-0.540703,-0.706139,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3775,0.596103,-0.123397,-0.138377,0.425166,-0.482111,-0.969241,-0.192715,0.58983,-0.130476,-0.999129,...,0.249356,1.029132,-0.332343,0.007998,0.618219,0.658851,0.080547,-1.026872,0.831986,0
3776,0.537198,0.610258,-0.373453,0.538863,-0.747154,-0.166254,0.288404,0.294042,0.368194,-0.951905,...,-0.056026,0.422636,1.029145,-0.796317,0.423893,0.317059,0.876707,-0.588022,0.72427,0
3777,0.586338,-0.61004,-0.464729,0.43172,-0.105702,-0.824378,-0.02586,0.778583,-0.846392,0.096839,...,0.248312,-0.153707,0.785722,0.598168,-0.390768,0.285832,-0.427053,-1.195046,0.259034,1
3778,0.427412,0.587215,-0.24888,0.233618,-0.722975,0.062959,0.574484,0.530069,0.023453,-0.02116,...,0.698019,0.59427,1.04469,0.244757,-0.623698,0.116014,0.038047,-0.73427,0.68405,1
3779,-0.001067,0.391166,-0.278283,0.789859,-0.309995,-1.201142,-0.379411,-0.028375,-0.169312,-0.530384,...,0.677638,-0.366761,0.345031,-0.839798,-0.150583,0.696749,-0.265417,-0.80158,1.510754,0

In [24]:
data=data.sample(frac=1)

In [25]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
1528,-0.232198,0.13213,0.096925,1.445417,-0.011512,-0.469353,-0.539951,0.568325,0.035491,-0.686042,...,0.684869,-0.064352,0.386022,0.726616,-0.476446,1.200558,-0.477488,-0.840568,1.03291,0
3570,0.636589,0.854563,-0.192765,0.522641,-0.445347,-0.26739,-0.379163,0.257799,0.932929,-0.728307,...,0.096517,-0.087516,-0.56114,-0.127627,0.058762,1.123969,-0.260675,-0.844632,1.593512,0
1805,0.171878,0.16391,-0.078525,0.4784,0.250688,-0.322073,-0.430583,0.401242,0.048955,-0.709374,...,0.068332,0.554532,0.341023,-0.764928,-0.0683,0.676946,-0.070612,0.226067,0.531696,0
1069,-0.563278,-0.60989,0.112375,0.465317,-0.85689,-0.288381,-0.479903,1.045721,0.095085,0.511692,...,0.813189,1.572031,0.367869,0.531527,-1.437005,-0.035752,-0.876054,0.185062,-0.200337,1
479,0.16085,-0.027895,-0.539029,0.328565,-1.550965,-0.309774,0.403868,0.986017,-0.34932,0.222773,...,1.040377,-1.201177,1.45231,0.683493,-0.111253,0.090806,-0.159967,-0.36684,0.630569,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472,-0.030886,0.68771,-0.727084,0.86179,-0.948694,-0.496047,-0.336143,-0.056612,-0.345357,-0.867717,...,1.038163,-0.713042,0.666477,-0.083109,0.180155,0.512022,0.15174,-1.114432,0.771864,1
2144,0.489062,0.310772,0.00393,0.901179,-0.206107,-0.735598,-0.692768,0.431393,0.073107,-0.807786,...,-0.030165,0.389948,-0.149004,-0.071061,0.001911,0.389074,0.106334,-0.506428,0.789649,0
2111,0.510265,-0.091756,-0.465875,0.692877,-0.253145,-0.771298,-0.060198,0.109926,0.293678,-0.429049,...,0.230531,0.375188,-0.219576,0.034605,-0.328423,0.528637,0.051914,-0.388579,0.782643,0
1335,-0.080096,-0.330203,0.586082,0.786734,0.179183,-0.699083,-0.146289,0.622758,0.051669,-0.846641,...,1.223011,0.827065,0.921351,-0.159757,-0.007713,0.468975,-0.055247,-0.003393,1.135373,0
1721,-0.131834,0.588638,-0.255511,0.991291,-0.7989,-0.565265,-0.12773,0.201873,-0.432611,-0.953648,...,0.958875,-0.260548,0.779857,-0.5084,0.397613,0.584964,0.535533,-0.433112,0.79831,1

In [26]:
data.to_csv("process1 train data after nlp(jhgan).csv")