In [1]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0521(final)/data/process/process1/process 1 test data row.csv",index_col=0)

In [2]:
data_row

                                                sentence  predict
3531    위임하실 경우에는 방문이나 내방 없이 드리는 전화 받으시고 전화 녹음를 통해서 대...      1.0
1400                                      네 그런 상황는 없을겁니다      0.0
802     지금 다짜고짜 여쭤보면 어떡합니까? 고객님 식별증도 접수도 안 해줬는데 그냥 로그...      1.0
3568                                  네 30분량에 3000돈입니다.       0.0
4531                           그 지역 사회에서 문의하기해 주셔야 합니다.       0.0
...                                                  ...      ...
2021    아 뭐 통장 전화숫자는 안 필요한가 그거는 이제 등록하고 뭐 여쭤봐야죠? 지금 다...      1.0
11184  국가 지원금 외에 해당 사항 자치단체가 자체 보조하는 금액을 합산할 사례 기준액 이...      0.0
15062                      별 언급을요 궁금한것 있으면 언제든 문의 해 주세요.      0.0
6475                        네, 직접 거주자중심로 가셔야다만 가능성 있음하네요      0.0
1804    사장님께서 혹시 안쓰시는 입출금 계정가 있으시면 저희가 월 400에서 450만원까...      1.0

[300 rows x 2 columns]

In [3]:
data_row.isnull().sum()

sentence    0
predict     0
dtype: int64

In [4]:
data=data_row.sample(frac=1)

In [5]:
data

                                                sentence  predict
8955    지금 다짜고짜 여쭤보면 어떡합니까? 고객님 신분 증명서도 접수도 안 해줬는데 그냥...      1.0
8830                  목줄은 보호자가 통제가능성 있음한 범위로 조절하시간면 됩니다.      0.0
791     아 아. 왜냐면 솔직히 이게 보이스보이스피싱 공격 같기도 하고 20만원 큰 자본도...      1.0
92      사장님께서 혹시 안쓰시는 입출금 입출금 계좌가 있으시면 저희가 월 400에서 45...      1.0
8192             네 로그인 계정에 자본을 다 빼가셨더라고요 바로?네 여보세요? 여보세요      1.0
...                                                  ...      ...
10912                                아니요 pc로그냥 접속할 수 있어요      0.0
1728                       그렇구나... 대리님 네 사기 행위 행위치지 마시고요      1.0
5128             인터넷 발행은 국민건강보험 사이버민원조직 사이트에서 가능성 있음합니다.      0.0
378                                  현재는 가입 신청기간이 마감됐어요.      0.0
1524                       위택스, 스마트위택스에서 가입 신청 하시간면 됩니다.      0.0

[300 rows x 2 columns]

In [6]:
data.to_csv("process1 test data before nlp(base).csv")

In [7]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

In [8]:
data.isnull().sum()

sentence    0
predict     0
dtype: int64

In [9]:
A=model.encode(data.iloc[0,0])

In [10]:
A.shape[0]

768

In [11]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [12]:
x_train=pd.DataFrame(index=range(0,data.shape[0]),columns=list)

In [13]:
x_train.shape

(300, 768)

In [14]:

y_train=pd.DataFrame(index=range(0,x_train.shape[0]),columns=['predict'])

In [15]:

x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
y_train

    predict
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
..      ...
295     NaN
296     NaN
297     NaN
298     NaN
299     NaN

[300 rows x 1 columns]

In [17]:
for i in range(data.shape[0]):
    y_train.iloc[i,0]=data.iloc[i,1]

In [18]:
y_train

    predict
0       1.0
1       0.0
2       1.0
3       1.0
4       1.0
..      ...
295     0.0
296     1.0
297     0.0
298     0.0
299     0.0

[300 rows x 1 columns]

In [19]:
y_train.isnull().sum()

predict    0
dtype: int64

In [20]:
for i in range(data.shape[0]):
    vector=[]
    vector=model.encode(data.iloc[i,0])
    for j in range(x_train.shape[1]):
        x_train.iloc[i,j]=vector[j]

In [21]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.06529,-0.048691,-0.004633,0.02411,0.002434,-0.007785,0.002989,0.010038,0.062214,-0.00158,...,0.000838,-0.008246,0.019792,0.026359,-0.038309,-0.063691,-0.000469,0.017153,0.002599,-0.027267
1,0.044554,-0.090142,-0.018002,-0.003301,0.00124,-0.016682,-0.017381,0.017512,0.035771,-0.010646,...,-0.059652,-0.039813,-0.019075,0.002306,-0.036743,-0.052907,0.025897,0.025113,0.007883,-0.014991
2,0.046942,-0.055731,-0.018847,0.008328,0.018601,-0.005779,0.001869,0.014437,0.060518,0.036524,...,-0.039456,-0.024509,-0.038338,-0.009602,-0.026188,0.011157,0.011527,0.032864,-0.025166,-0.041499
3,0.061531,-0.056895,-0.017051,0.033785,0.023331,-0.005497,-0.010168,0.031941,0.037238,-0.023113,...,-0.036403,-0.014727,0.004123,0.034268,-0.013538,0.005024,0.044065,0.052899,-0.0646,-0.029389
4,0.093691,-0.064663,-0.025898,0.046793,0.017633,-0.001729,-0.042047,0.046694,0.076629,-0.009799,...,-0.005398,0.010216,-0.008072,0.004552,-0.02693,-0.057094,-0.014213,0.02137,0.003092,-0.008648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.054564,-0.035742,-0.012474,0.001655,0.062159,-0.002796,-0.039626,0.022133,0.059766,-0.034495,...,-0.011598,-0.001748,0.027827,0.008969,-0.065164,-0.077576,-0.001017,0.028452,0.027204,-0.029363
296,0.045379,-0.00036,-0.038068,0.021346,0.046335,0.008896,-0.06224,0.029109,0.068862,-0.011445,...,-0.01064,-0.013419,0.017811,-0.008298,-0.05693,-0.038662,-0.036975,0.013656,0.02832,-0.036056
297,0.029257,-0.094823,-0.019293,-0.014863,-0.005434,-0.008754,0.006066,-0.004757,0.046517,-0.016336,...,-0.055045,-0.044303,-0.018142,0.00699,-0.027283,-0.04873,0.017779,0.022537,-0.000517,-0.01938
298,0.024622,-0.038435,-0.015564,0.002004,0.022771,-0.006975,-0.061473,0.040351,0.065428,-0.010774,...,-0.046939,-0.034656,0.005575,-0.016387,-0.049853,-0.043829,0.013915,0.027833,0.048824,-0.024518
299,0.061233,-0.038882,-0.017587,0.021353,0.044214,-0.004147,-0.069593,0.031897,0.081568,-0.00832,...,-0.028651,-0.013104,0.025428,-0.020917,-0.06274,-0.047013,0.021399,0.022796,0.029151,-0.026979

In [22]:
data=pd.concat([x_train,y_train],axis=1)

In [23]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
0,0.06529,-0.048691,-0.004633,0.02411,0.002434,-0.007785,0.002989,0.010038,0.062214,-0.00158,...,-0.008246,0.019792,0.026359,-0.038309,-0.063691,-0.000469,0.017153,0.002599,-0.027267,1.0
1,0.044554,-0.090142,-0.018002,-0.003301,0.00124,-0.016682,-0.017381,0.017512,0.035771,-0.010646,...,-0.039813,-0.019075,0.002306,-0.036743,-0.052907,0.025897,0.025113,0.007883,-0.014991,0.0
2,0.046942,-0.055731,-0.018847,0.008328,0.018601,-0.005779,0.001869,0.014437,0.060518,0.036524,...,-0.024509,-0.038338,-0.009602,-0.026188,0.011157,0.011527,0.032864,-0.025166,-0.041499,1.0
3,0.061531,-0.056895,-0.017051,0.033785,0.023331,-0.005497,-0.010168,0.031941,0.037238,-0.023113,...,-0.014727,0.004123,0.034268,-0.013538,0.005024,0.044065,0.052899,-0.0646,-0.029389,1.0
4,0.093691,-0.064663,-0.025898,0.046793,0.017633,-0.001729,-0.042047,0.046694,0.076629,-0.009799,...,0.010216,-0.008072,0.004552,-0.02693,-0.057094,-0.014213,0.02137,0.003092,-0.008648,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.054564,-0.035742,-0.012474,0.001655,0.062159,-0.002796,-0.039626,0.022133,0.059766,-0.034495,...,-0.001748,0.027827,0.008969,-0.065164,-0.077576,-0.001017,0.028452,0.027204,-0.029363,0.0
296,0.045379,-0.00036,-0.038068,0.021346,0.046335,0.008896,-0.06224,0.029109,0.068862,-0.011445,...,-0.013419,0.017811,-0.008298,-0.05693,-0.038662,-0.036975,0.013656,0.02832,-0.036056,1.0
297,0.029257,-0.094823,-0.019293,-0.014863,-0.005434,-0.008754,0.006066,-0.004757,0.046517,-0.016336,...,-0.044303,-0.018142,0.00699,-0.027283,-0.04873,0.017779,0.022537,-0.000517,-0.01938,0.0
298,0.024622,-0.038435,-0.015564,0.002004,0.022771,-0.006975,-0.061473,0.040351,0.065428,-0.010774,...,-0.034656,0.005575,-0.016387,-0.049853,-0.043829,0.013915,0.027833,0.048824,-0.024518,0.0
299,0.061233,-0.038882,-0.017587,0.021353,0.044214,-0.004147,-0.069593,0.031897,0.081568,-0.00832,...,-0.013104,0.025428,-0.020917,-0.06274,-0.047013,0.021399,0.022796,0.029151,-0.026979,0.0

In [24]:
data=data.sample(frac=1)

In [25]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
14,0.042143,-0.075863,-0.032787,-0.034326,0.003703,0.001564,0.03988,-0.019157,0.063523,-0.016634,...,-0.05513,-0.023732,0.026815,-0.030726,-0.047846,0.02226,0.011164,0.014285,-0.00638,0.0
192,0.093584,-0.010127,-0.02918,0.001598,0.000396,-0.002416,-0.017291,0.017797,0.082248,-0.023267,...,-0.024688,-0.003001,-0.000911,-0.040665,-0.051432,-0.004543,0.049485,0.014501,-0.026474,1.0
185,0.050962,-0.023021,-0.014449,0.000745,0.047686,0.01924,-0.090667,0.032218,0.092098,0.000602,...,-0.025599,0.024939,-0.019021,-0.055165,-0.041121,0.018082,0.017464,0.031786,-0.02708,0.0
28,0.040677,-0.095884,-0.025877,-0.01286,0.006696,-0.012739,-0.006766,-0.010695,0.060887,-0.00101,...,0.023425,-0.033546,0.013293,-0.010766,-0.018231,0.005803,0.03083,-0.007609,-0.01767,1.0
83,0.058986,-0.036946,-0.02548,-0.006198,0.014244,0.001092,-0.048714,0.027927,0.056201,-0.013811,...,-0.026212,-0.034943,0.00211,-0.013898,-0.040588,0.017561,0.022851,0.00725,-0.021191,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,0.041226,-0.067227,-0.006068,-0.027994,0.037467,0.002795,-0.009585,0.007646,0.069293,-0.023132,...,-0.032661,0.026757,0.012142,-0.052688,-0.052194,0.015045,0.022258,0.021265,-0.022555,0.0
222,0.067222,-0.054213,-0.030217,-0.014232,-0.004994,0.00241,0.036261,-0.024642,0.055866,-0.004851,...,-0.031071,-0.024941,0.026737,-0.03427,-0.049872,0.028103,0.003819,0.005779,-0.035805,0.0
66,0.086307,-0.040818,-0.026465,0.009861,0.011541,-0.00645,-0.013623,0.010029,0.080842,-0.016113,...,-0.020386,0.010085,0.022582,-0.045778,-0.058397,0.004633,0.029271,0.002256,-0.021711,1.0
183,0.027199,-0.035164,-0.005944,0.001627,0.024499,-0.003586,-0.070054,0.027453,0.049519,-0.012694,...,-0.041706,0.004206,-0.017663,-0.041342,-0.057198,0.012646,0.030903,0.042105,-0.014678,0.0
176,0.059343,-0.054728,-0.028986,-0.007379,0.010191,-0.007186,-0.000033,-0.012047,0.056827,0.007244,...,-0.037772,-0.004522,0.006268,-0.046143,-0.037248,0.009444,0.022435,0.01914,-0.033461,0.0

In [26]:
data.to_csv("process1 test data after nlp(base).csv")