In [1]:
import pandas as pd

data=pd.read_csv('/Users/withmocha/Desktop/VisualStudioCode/Capstone Design project/Data/normal/data_word_fine.csv')

data

,Unnamed: 0,word1,word2
0,0,"['해결', '남', '부담']","['해결', '남', '부담']"
1,1,"['이번', '달', '급여', '물가', '월급', '화', '나']","['최대한', '지출', '억제', '월급', '고정', '지출', '수', '것']"
2,2,"['회사', '신입', '말투', '애', '생각', '스트레스']","['사람', '것', '거리', '예의', '스트레스', '것']"
3,3,"['직장', '막내', '이유', '나', '심부름', '일', '데']","['직장', '사람', '이야기', '일', '데', '방해']"
4,4,"['얼마', '전', '입사', '신입', '사원', '나', '무시', '것', ...","['상사', '나', '인사', '인사']"
...,...,...,...
51625,51625,"['나이', '돈', '능력']","['아무것', '수', '가치', '실망']"
51626,51626,"['몸', '전', '일', '것', '짜증']","['마음', '수', '일', '이젠', '몸', '주니']"
51627,51627,"['남편', '노후', '준비', '미래', '걱정']","['주변', '사람', '노후', '준비', '난']"
51628,51628,"['십', '년', '남편', '이혼', '동안', '세월', '배신감', '화',...","['수', '일', '불만']"
51629,51629,"['남편', '결혼', '지', '사', '십', '년', '사람', '것', '사람']","['사람', '것', '사람', '의심', '말']"

In [3]:
import konlpy
from konlpy.tag import Mecab
nlp_model = Mecab()

In [4]:
Y=pd.DataFrame(index=range(0,data.shape[0]),columns=['predict'])