In [1]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/final/process2/test/process2 test data row.csv",index_col=0)

In [2]:
data_row

                                              sentence  predict
71    재판장에서. 제가 이제 본인 담당 수사관인데 제가 녹취 테이프 작성해 드리면 그 ...        1
753   왜냐면은 지금 변장을 하고 들어와가지고 신원 조회가 좀 불가능했습니다. 아시겠죠?...        1
789   이제 본인 명의로 돼있는 통장들 중에 대포 통장과 불법 자금에 대해서 이제 계좌 ...        1
359   아니에요. 유선상으로 대출할 때는 찾아가는 거는 최하위 우선 순위 실행입니다 음 ...        0
554   아 네 예 알겠습니다. 조금만 기다려 전화는 호주머니에 넣고 이동하시겠습니다 네 ...        1
..                                                 ...      ...
321   어떤 그 스마트 보안 센터를 클릭 하셨는데 열 수 없는 페이지 라고 나오신다고요?...        1
549   아 아. 왜냐면 솔직히 이게 보이스피싱 같기도 하고 20만원 큰 돈도 아니겠지만 ...        0
144   사장님께서 혹시 안쓰시는 계좌가 있으시면 저희가 월 400에서 450만원까지 선지...        0
197   그래서 말씀 드리잖아요. 20만원 넣지 않으셔도 되고요. 변호사 선임해주시고 연락...        0
922   예 예 예. 사건번호가요. 2017 형제. 형제? 형제? 예 예. 형제. 5290...        1

[300 rows x 2 columns]

In [3]:
data_row.isnull().sum()

sentence    0
predict     0
dtype: int64

In [4]:
data=data_row.sample(frac=1)

In [5]:
data

                                               sentence  predict
1012   음 그럼 일단 오늘 받는거는 그럼 고소장 받는거는 그냥 그럼 제가 읽어보는 거에요...        1
656    주문하신 게? 사람이 많이 밀려있나요? 아니 그렇게 많은건 아닌데. 조금 오래 걸...        1
794    1월 4일입니다 네 작성하셨나요? 네 알겠습니다. 그러면 지금 머리 속으로 13시...        1
288    네 그게 지금 고객센터로 넘어가는게 좀 서류가 늦게 들어가서 확인이 안되실수도 있...        0
160    모바일 뱅킹은 농협만 사용하시나? 피해자 :\u3000네 OTP소지 하세요 보안카...        1
...                                                 ...      ...
753    왜냐면은 지금 변장을 하고 들어와가지고 신원 조회가 좀 불가능했습니다. 아시겠죠?...        1
1082   네 검색하셨다면 이제 저희 서울 중앙 지방 검찰청뜨시죠. 네 네 거기 한번 클릭 ...        1
976    과거에 근데 뭐 법정 재판에 회부가 되셨다던가 검찰 조사 받은 이력이 있을까요? ...        1
385    네 네 이거 안된데요. 이거 지금 국민은행가서 해야 한다는데. 지금 국민은행 가고...        1
65     예 각각의 계좌가 본인 계좌가 맞으시면 오늘 현재로 계략적인 잔액을 기억을 할 거...        1

[300 rows x 2 columns]

In [6]:
data.to_csv("process2 test data before nlp(jhgan).csv")

In [7]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('jhgan/ko-sbert-sts')

In [8]:
data.isnull().sum()

sentence    0
predict     0
dtype: int64

In [9]:
A=model.encode(data.iloc[0,0])

In [10]:
A.shape[0]

768

In [11]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [12]:
x_train=pd.DataFrame(index=range(0,data.shape[0]),columns=list)

In [13]:
x_train.shape

(300, 768)

In [14]:

y_train=pd.DataFrame(index=range(0,x_train.shape[0]),columns=['predict'])

In [15]:

x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
y_train

    predict
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
..      ...
295     NaN
296     NaN
297     NaN
298     NaN
299     NaN

[300 rows x 1 columns]

In [17]:
for i in range(data.shape[0]):
    y_train.iloc[i,0]=data.iloc[i,1]

In [18]:
y_train

    predict
0         1
1         1
2         1
3         0
4         1
..      ...
295       1
296       1
297       1
298       1
299       1

[300 rows x 1 columns]

In [19]:
y_train.isnull().sum()

predict    0
dtype: int64

In [20]:
for i in range(data.shape[0]):
    vector=[]
    vector=model.encode(data.iloc[i,0])
    for j in range(x_train.shape[1]):
        x_train.iloc[i,j]=vector[j]

In [21]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.423357,0.329552,-0.220208,0.042673,-0.542395,0.069796,-0.417581,0.135359,-0.211774,-0.030308,...,0.266414,0.55057,0.519407,0.420894,0.347484,-0.224359,0.588289,0.197574,0.121947,0.202408
1,0.492194,0.212017,-0.066997,0.053507,-0.470779,-0.81717,-0.118232,0.099965,-0.415901,-0.681026,...,-0.034504,0.282543,-0.253773,0.581378,-0.670946,-0.144551,0.228544,0.211777,-1.031725,1.03366
2,0.419327,-0.037936,-0.524722,0.634453,-0.537025,-0.211861,-0.15369,-0.457005,-0.265817,-0.130254,...,0.505243,1.17072,-0.197476,-0.576634,0.398416,-1.484877,0.342202,-0.275265,-1.19749,0.74815
3,0.621171,0.890093,0.035081,1.029984,-0.422219,-0.213758,0.155532,0.063191,0.465531,0.60187,...,0.505283,1.354563,0.210606,0.475538,-0.403834,-0.399109,0.926406,0.513794,-0.244504,0.693274
4,0.039357,0.95272,-0.062829,0.57464,-0.791399,-0.610748,0.15143,0.646245,-0.058976,-0.043719,...,0.065939,1.130071,0.268555,0.800605,0.146235,-0.272046,-0.103565,-0.439818,-0.543924,0.358218
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.253675,0.855388,0.157911,0.558371,-1.000662,-0.717478,0.26954,0.598133,-0.229515,-0.329403,...,-0.36149,1.012082,0.106556,0.912132,-0.370331,-0.339863,-0.15765,-0.306764,-0.341591,0.480651
296,-0.857381,0.095771,0.456598,0.589936,-0.185549,0.065896,0.305553,0.219226,-0.376502,0.571409,...,0.45985,0.337366,-0.338611,0.280206,0.313776,-0.630609,1.057353,-0.347879,-0.567393,1.53916
297,0.392639,0.105087,-0.074216,0.470783,0.16389,-0.413173,0.020901,1.067858,-0.401926,-0.762066,...,-0.129489,0.194652,0.764018,1.606246,-0.599838,-0.370297,0.242406,0.105176,0.030531,0.611139
298,0.595339,-0.166591,-0.019825,0.860969,-0.664809,-0.58191,-0.076022,1.106262,-0.256829,0.288667,...,-0.125885,0.244792,0.012105,1.18474,-0.355844,-0.59579,0.251483,-0.23934,-0.688472,-0.119367
299,0.087169,0.107663,-0.155283,0.929886,-0.760935,-0.707099,-0.46826,0.634196,-0.192084,0.320845,...,0.105447,0.600322,0.521855,1.395414,0.726232,-0.364915,0.452287,-0.317384,-0.436512,-0.095842

In [22]:
data=pd.concat([x_train,y_train],axis=1)

In [23]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
0,0.423357,0.329552,-0.220208,0.042673,-0.542395,0.069796,-0.417581,0.135359,-0.211774,-0.030308,...,0.55057,0.519407,0.420894,0.347484,-0.224359,0.588289,0.197574,0.121947,0.202408,1
1,0.492194,0.212017,-0.066997,0.053507,-0.470779,-0.81717,-0.118232,0.099965,-0.415901,-0.681026,...,0.282543,-0.253773,0.581378,-0.670946,-0.144551,0.228544,0.211777,-1.031725,1.03366,1
2,0.419327,-0.037936,-0.524722,0.634453,-0.537025,-0.211861,-0.15369,-0.457005,-0.265817,-0.130254,...,1.17072,-0.197476,-0.576634,0.398416,-1.484877,0.342202,-0.275265,-1.19749,0.74815,1
3,0.621171,0.890093,0.035081,1.029984,-0.422219,-0.213758,0.155532,0.063191,0.465531,0.60187,...,1.354563,0.210606,0.475538,-0.403834,-0.399109,0.926406,0.513794,-0.244504,0.693274,0
4,0.039357,0.95272,-0.062829,0.57464,-0.791399,-0.610748,0.15143,0.646245,-0.058976,-0.043719,...,1.130071,0.268555,0.800605,0.146235,-0.272046,-0.103565,-0.439818,-0.543924,0.358218,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.253675,0.855388,0.157911,0.558371,-1.000662,-0.717478,0.26954,0.598133,-0.229515,-0.329403,...,1.012082,0.106556,0.912132,-0.370331,-0.339863,-0.15765,-0.306764,-0.341591,0.480651,1
296,-0.857381,0.095771,0.456598,0.589936,-0.185549,0.065896,0.305553,0.219226,-0.376502,0.571409,...,0.337366,-0.338611,0.280206,0.313776,-0.630609,1.057353,-0.347879,-0.567393,1.53916,1
297,0.392639,0.105087,-0.074216,0.470783,0.16389,-0.413173,0.020901,1.067858,-0.401926,-0.762066,...,0.194652,0.764018,1.606246,-0.599838,-0.370297,0.242406,0.105176,0.030531,0.611139,1
298,0.595339,-0.166591,-0.019825,0.860969,-0.664809,-0.58191,-0.076022,1.106262,-0.256829,0.288667,...,0.244792,0.012105,1.18474,-0.355844,-0.59579,0.251483,-0.23934,-0.688472,-0.119367,1
299,0.087169,0.107663,-0.155283,0.929886,-0.760935,-0.707099,-0.46826,0.634196,-0.192084,0.320845,...,0.600322,0.521855,1.395414,0.726232,-0.364915,0.452287,-0.317384,-0.436512,-0.095842,1

In [24]:
data=data.sample(frac=1)

In [25]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
262,0.36342,0.730122,0.151181,0.507314,0.245331,-0.192631,0.246801,1.12842,-0.149834,0.106403,...,0.592825,0.50064,0.605496,0.27481,-0.42649,0.086146,-0.3549,-0.387442,0.34969,1
296,-0.857381,0.095771,0.456598,0.589936,-0.185549,0.065896,0.305553,0.219226,-0.376502,0.571409,...,0.337366,-0.338611,0.280206,0.313776,-0.630609,1.057353,-0.347879,-0.567393,1.53916,1
40,0.179474,-0.11769,-0.040403,0.270527,-0.956704,0.307182,-0.280904,0.131339,0.052337,0.431257,...,0.270138,0.223051,1.047092,0.448527,0.259045,0.628844,-0.650998,-0.096991,0.466812,1
58,-0.695436,-0.036932,0.191028,-0.018038,-0.157643,-0.090875,-0.447116,0.502523,0.262692,0.785634,...,0.562066,-0.322386,0.485369,0.264875,-0.923644,0.986652,-0.807359,0.42634,1.188043,1
231,-0.174728,-0.442657,-0.122642,0.808087,-0.949525,-0.00288,0.603051,0.444048,-0.069144,0.375298,...,0.666232,-0.090251,0.564425,0.76861,-0.796792,0.713367,-0.325073,-0.580606,1.201177,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,0.703024,0.043034,-0.449081,0.369961,-0.956316,-0.721727,-0.023087,0.196514,-0.07202,-0.577474,...,0.241416,-0.263029,0.70499,0.319108,0.21258,-0.275676,0.330456,-0.238615,0.310781,0
119,0.10497,0.203703,0.096283,0.903566,-0.772838,-0.467643,0.30681,0.293102,0.527462,0.207893,...,1.086128,0.309299,0.986482,-0.342356,-0.73332,-0.393184,-0.124059,-0.355277,0.166317,1
114,-0.010012,-0.703465,-0.350885,0.815017,-0.063878,-0.583349,-0.172727,0.571138,-0.063338,-0.092572,...,0.452037,0.224393,0.736956,-0.599168,-0.002092,0.165986,-0.055533,-0.349888,0.136336,0
212,-0.184607,0.22061,0.221541,0.074137,-0.665925,-0.805915,0.294412,0.32417,0.087962,0.502689,...,0.697795,0.145734,1.586126,0.179109,-0.405893,0.292017,0.040584,0.130968,0.705416,1
1,0.492194,0.212017,-0.066997,0.053507,-0.470779,-0.81717,-0.118232,0.099965,-0.415901,-0.681026,...,0.282543,-0.253773,0.581378,-0.670946,-0.144551,0.228544,0.211777,-1.031725,1.03366,1

In [26]:
data.to_csv("process2 test data after nlp(jhgan).csv")