In [1]:
import os
from openai import OpenAI
import pandas as pd

In [2]:
data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0504/gpt/train/sentence 4/train_data_before_vector.csv",index_col=0)
data_row

                                                sentence  predict
17414                    인천,김해,제주 공항에 국제운전면허 발급센터도 있습니다.        0
13248                             국립중앙박물관 홈페이지에서 가능합니다.         0
2913    저희가 주민 번호 은행권에 계좌 번호 비밀 번호 등을 묻지 않는다고 말씀... 아...        2
13131                                          네 그러시군요.         0
817     피해자 :폐쇠한 것 같 아요 그거자체 를. 음 신한 은행은 신한 은행은 제가 기억...        2
...                                                  ...      ...
1153    좀. 제가 지금까지 대출을 받은거 다 아시겠지만 받으면은 제외하거나 빼서 들어오지...        1
9952   물론입니다. 제보자님께 해가 가지않도록 비리신고제도를 운영하고 있고 보호 제도를 마...        0
2451                                 자녀분들의 나이가 어떻게 되시나요?        0
1430    발생한 비용에 대해서이자라든지 금액적인 부분에 대해서 본인께서 걱정하실 필요없구요...        2
390     예 예 그리고 신분증 앞 면 2가지 사진 찍어서 카톡으로 좀 보내 주시구요. 카카...        1

[10244 rows x 2 columns]

In [3]:
data_row=data_row[:3000]

In [23]:
Y=pd.DataFrame(index=range(data_row.shape[0]),columns=['predict'])

In [27]:
for i in range(data_row.shape[0]):
    Y.iloc[i,0]=data_row.iloc[i,1]

### 일반=0/대출사기형=1/수사기관형=2   gpt4 한번 질문하는데 2.2917076원

In [28]:
Y

     predict
0          0
1          0
2          2
3          0
4          2
...      ...
2995       1
2996       0
2997       0
2998       0
2999       2

[3000 rows x 1 columns]

In [9]:
from sentence_transformers import SentenceTransformer


model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

In [10]:
A=model.encode(data_row.iloc[0,0])

In [11]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [12]:
x_train=pd.DataFrame(index=range(0,data_row.shape[0]),columns=list)

In [13]:
for i in range(data_row.shape[0]):
    vector=[]
    vector=model.encode(data_row.iloc[i,0])
    for j in range(x_train.shape[1]):
        x_train.iloc[i,j]=vector[j]

In [14]:
X=x_train

In [15]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.052607,-0.053146,-0.012321,-0.014028,0.00689,-0.004457,-0.028779,0.008729,0.079076,-0.018651,...,-0.043108,-0.035216,-0.004926,0.002643,-0.041705,-0.073804,0.011732,0.023657,0.023674,-0.021644
1,0.06564,-0.056633,-0.012326,-0.016592,-0.000792,0.000747,-0.054616,0.016118,0.057677,-0.018877,...,-0.039779,-0.044232,-0.005241,0.006694,-0.043336,-0.056174,0.029313,0.019381,0.020676,-0.005578
2,0.069203,0.005305,-0.026596,0.008959,0.006379,0.003055,-0.019259,0.008808,0.090986,-0.012824,...,-0.005861,0.003346,0.024238,-0.002917,-0.040966,-0.080141,0.006348,0.023794,0.016556,-0.028141
3,0.048832,-0.030371,-0.013756,-0.014487,0.036973,0.022373,-0.071002,0.022927,0.065173,-0.012395,...,-0.019117,-0.019971,0.005966,-0.027569,-0.053896,-0.080093,-0.018758,0.014429,0.03731,-0.016282
4,0.046536,-0.022251,-0.027004,0.025981,0.022376,-0.013689,-0.050304,0.025515,0.044787,0.012179,...,-0.053641,-0.000852,0.002012,0.01753,-0.016844,-0.010146,-0.008205,0.021647,0.003026,-0.051527
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.103314,-0.055173,-0.020592,0.040117,0.033047,0.013462,-0.041553,0.026483,0.07764,-0.022566,...,0.000349,-0.004895,-0.002905,0.013308,-0.044995,-0.075419,0.004471,0.01453,0.021715,-0.006937
2996,0.067874,-0.063887,-0.029778,-0.007054,0.036702,-0.005829,-0.014136,0.001677,0.047928,-0.010099,...,-0.025758,-0.035204,-0.003959,0.004056,-0.057046,-0.048743,-0.001795,0.026904,0.016072,-0.034152
2997,0.050919,-0.081113,-0.025674,-0.021389,-0.005436,-0.005959,0.013455,-0.004437,0.058308,-0.006634,...,-0.04064,-0.033325,-0.022092,0.022104,-0.035005,-0.049889,0.017549,0.018456,0.00625,-0.027227
2998,0.033868,-0.028757,-0.018064,-0.003613,0.036243,-0.017056,-0.072555,0.026048,0.054409,-0.012396,...,-0.03354,-0.021542,0.036983,-0.019718,-0.032257,-0.06877,0.019108,0.026003,0.019968,-0.025191
2999,0.048005,-0.016399,-0.032178,0.026566,0.01723,0.020571,-0.026939,-0.005646,0.103374,-0.016679,...,0.031263,0.002791,-0.000114,0.010979,-0.034349,-0.006738,-0.030371,0.035596,0.028135,-0.023273

In [20]:
Y.shape

(3000, 1)

In [21]:
x_train.shape

(3000, 768)

In [29]:
data_save=pd.concat([x_train,Y],axis=1)

In [30]:
data_save

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
0,0.052607,-0.053146,-0.012321,-0.014028,0.00689,-0.004457,-0.028779,0.008729,0.079076,-0.018651,...,-0.035216,-0.004926,0.002643,-0.041705,-0.073804,0.011732,0.023657,0.023674,-0.021644,0
1,0.06564,-0.056633,-0.012326,-0.016592,-0.000792,0.000747,-0.054616,0.016118,0.057677,-0.018877,...,-0.044232,-0.005241,0.006694,-0.043336,-0.056174,0.029313,0.019381,0.020676,-0.005578,0
2,0.069203,0.005305,-0.026596,0.008959,0.006379,0.003055,-0.019259,0.008808,0.090986,-0.012824,...,0.003346,0.024238,-0.002917,-0.040966,-0.080141,0.006348,0.023794,0.016556,-0.028141,2
3,0.048832,-0.030371,-0.013756,-0.014487,0.036973,0.022373,-0.071002,0.022927,0.065173,-0.012395,...,-0.019971,0.005966,-0.027569,-0.053896,-0.080093,-0.018758,0.014429,0.03731,-0.016282,0
4,0.046536,-0.022251,-0.027004,0.025981,0.022376,-0.013689,-0.050304,0.025515,0.044787,0.012179,...,-0.000852,0.002012,0.01753,-0.016844,-0.010146,-0.008205,0.021647,0.003026,-0.051527,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0.103314,-0.055173,-0.020592,0.040117,0.033047,0.013462,-0.041553,0.026483,0.07764,-0.022566,...,-0.004895,-0.002905,0.013308,-0.044995,-0.075419,0.004471,0.01453,0.021715,-0.006937,1
2996,0.067874,-0.063887,-0.029778,-0.007054,0.036702,-0.005829,-0.014136,0.001677,0.047928,-0.010099,...,-0.035204,-0.003959,0.004056,-0.057046,-0.048743,-0.001795,0.026904,0.016072,-0.034152,0
2997,0.050919,-0.081113,-0.025674,-0.021389,-0.005436,-0.005959,0.013455,-0.004437,0.058308,-0.006634,...,-0.033325,-0.022092,0.022104,-0.035005,-0.049889,0.017549,0.018456,0.00625,-0.027227,0
2998,0.033868,-0.028757,-0.018064,-0.003613,0.036243,-0.017056,-0.072555,0.026048,0.054409,-0.012396,...,-0.021542,0.036983,-0.019718,-0.032257,-0.06877,0.019108,0.026003,0.019968,-0.025191,0
2999,0.048005,-0.016399,-0.032178,0.026566,0.01723,0.020571,-0.026939,-0.005646,0.103374,-0.016679,...,0.002791,-0.000114,0.010979,-0.034349,-0.006738,-0.030371,0.035596,0.028135,-0.023273,2

In [31]:
data_save.to_csv("NO gpt train data.csv")