In [1]:
import pandas as pd

data_row=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0521(final)/data/process/process1/process 1 test data row.csv",index_col=0)

In [2]:
data_row

                                                sentence  predict
3531    위임하실 경우에는 방문이나 내방 없이 드리는 전화 받으시고 전화 녹음를 통해서 대...      1.0
1400                                      네 그런 상황는 없을겁니다      0.0
802     지금 다짜고짜 여쭤보면 어떡합니까? 고객님 식별증도 접수도 안 해줬는데 그냥 로그...      1.0
3568                                  네 30분량에 3000돈입니다.       0.0
4531                           그 지역 사회에서 문의하기해 주셔야 합니다.       0.0
...                                                  ...      ...
2021    아 뭐 통장 전화숫자는 안 필요한가 그거는 이제 등록하고 뭐 여쭤봐야죠? 지금 다...      1.0
11184  국가 지원금 외에 해당 사항 자치단체가 자체 보조하는 금액을 합산할 사례 기준액 이...      0.0
15062                      별 언급을요 궁금한것 있으면 언제든 문의 해 주세요.      0.0
6475                        네, 직접 거주자중심로 가셔야다만 가능성 있음하네요      0.0
1804    사장님께서 혹시 안쓰시는 입출금 계정가 있으시면 저희가 월 400에서 450만원까...      1.0

[300 rows x 2 columns]

In [3]:
data_row.isnull().sum()

sentence    0
predict     0
dtype: int64

In [4]:
data=data_row.sample(frac=1)

In [5]:
data

                                                sentence  predict
16163  온라인 결제가능성 있음 힘콕상품권은 11업무 발행되며 1인 최대 10오직금액 15퍼...      0.0
5958    다른거 필요한 건 없나요? 뭐 추가적인 접수는 없으세요 아 뭐 통장 식별연락처는 ...      1.0
9312    예 차후에 변동 안 되세요 예 대출 승인 나셨을 경우에 대출금 송금 받아 보실 수...      1.0
11778                                인증 결과 현재 미납인 상황입니다.      0.0
15753             주민등록세액의 10% (인구 50다만 이상함 시각 25%)되겠습니다.      0.0
...                                                  ...      ...
8848                 그러시기면 직장인건강검진 실시하는 의료기관에서 받으시면 됩니다.      0.0
1182   단속반이 수시로 나가고 있는데 단속반이 없는 사이 불법주정차들을 한사물 같아요.죄송...      0.0
9640    아 뭐 통장 식별식별번호는 안 필요한가 그거는 이제 등록하고 뭐 여쭤봐야죠? 지금...      1.0
1609    수납 담당자님 은행 아이디 연락처는 바로 카카오톡으로 보내드릴거구요. 수납 가능하...      1.0
3568                                  네 30분량에 3000돈입니다.       0.0

[300 rows x 2 columns]

In [6]:
data.to_csv("process1 test data before nlp(jhgan).csv")

In [7]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('jhgan/ko-sbert-sts')

In [8]:
data.isnull().sum()

sentence    0
predict     0
dtype: int64

In [9]:
A=model.encode(data.iloc[0,0])

In [10]:
A.shape[0]

768

In [11]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [12]:
x_train=pd.DataFrame(index=range(0,data.shape[0]),columns=list)

In [13]:
x_train.shape

(300, 768)

In [14]:

y_train=pd.DataFrame(index=range(0,x_train.shape[0]),columns=['predict'])

In [15]:

x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
298,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
y_train

    predict
0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
..      ...
295     NaN
296     NaN
297     NaN
298     NaN
299     NaN

[300 rows x 1 columns]

In [17]:
for i in range(data.shape[0]):
    y_train.iloc[i,0]=data.iloc[i,1]

In [18]:
y_train

    predict
0       0.0
1       1.0
2       1.0
3       0.0
4       0.0
..      ...
295     0.0
296     0.0
297     1.0
298     1.0
299     0.0

[300 rows x 1 columns]

In [19]:
y_train.isnull().sum()

predict    0
dtype: int64

In [20]:
for i in range(data.shape[0]):
    vector=[]
    vector=model.encode(data.iloc[i,0])
    for j in range(x_train.shape[1]):
        x_train.iloc[i,j]=vector[j]

In [21]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.329451,0.431143,-0.367999,-0.169289,-1.394348,-0.145452,0.062584,-0.114825,-0.114544,-0.650955,...,0.952151,-0.325759,-0.997998,0.213895,0.239176,0.284676,0.31514,-1.136931,-0.507937,1.267687
1,0.390732,-0.261001,-0.149332,1.333708,-0.983257,-0.565741,-0.512015,1.300433,0.223589,-0.847713,...,-0.38884,0.890659,0.631862,1.411813,-0.928311,0.091868,0.044379,0.124163,-0.531913,0.373687
2,0.139611,0.645789,-0.116925,0.622768,-0.887756,-0.676442,-0.40996,0.424416,-0.279859,-0.167963,...,-0.505042,0.967508,0.191013,1.613483,0.655958,-0.526212,0.58489,0.200618,0.538254,0.850132
3,0.281479,-0.525071,0.130746,1.69893,-0.507978,-0.954367,1.16376,1.084302,-0.574299,-0.888963,...,0.493491,1.599201,1.540466,0.222635,-0.043235,0.052227,0.62466,-0.042933,0.046029,0.887284
4,0.528865,0.038423,-0.190186,0.277023,-0.382854,-0.832077,-0.439449,-0.355043,0.189325,-1.012242,...,0.789078,-0.542039,-0.231946,-0.451283,0.071639,0.498077,0.633925,-1.21094,-1.14928,1.792787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.63243,0.482682,-0.136232,0.918367,0.100855,-1.007706,-0.592897,0.257265,0.448209,-0.788035,...,-0.45428,-0.131837,0.501355,0.522778,0.06034,0.389447,0.19472,-0.602492,0.232616,0.702234
296,0.025844,0.165337,-0.245077,0.533705,-0.937285,-0.047996,0.29783,0.118942,-0.505983,-0.622844,...,-0.53054,0.8263,0.338435,1.488717,-0.550905,-0.9107,0.262096,-0.043678,-0.381346,0.096849
297,0.956626,-0.060599,-0.57058,0.763405,-1.484902,-0.810225,-0.417923,0.988698,0.071142,0.032354,...,-0.4386,0.875226,0.830815,1.044066,-0.348556,-0.019037,0.179124,0.17323,-0.505063,-0.331804
298,-0.008378,0.062715,-0.706405,0.500612,-0.943396,-0.004417,0.260453,0.118727,0.699558,-0.898232,...,0.163404,0.580136,0.46051,0.15662,-0.441507,-0.436369,0.28289,0.526717,-0.245964,0.54091
299,1.173891,-1.19603,-0.31596,-1.20352,-0.346901,0.482871,-1.414486,-0.182644,0.4339,-1.154886,...,-0.424879,0.219386,-0.042042,0.952729,-0.612921,-0.182906,0.938066,-0.590468,-1.599398,1.114622

In [22]:
data=pd.concat([x_train,y_train],axis=1)

In [23]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
0,0.329451,0.431143,-0.367999,-0.169289,-1.394348,-0.145452,0.062584,-0.114825,-0.114544,-0.650955,...,-0.325759,-0.997998,0.213895,0.239176,0.284676,0.31514,-1.136931,-0.507937,1.267687,0.0
1,0.390732,-0.261001,-0.149332,1.333708,-0.983257,-0.565741,-0.512015,1.300433,0.223589,-0.847713,...,0.890659,0.631862,1.411813,-0.928311,0.091868,0.044379,0.124163,-0.531913,0.373687,1.0
2,0.139611,0.645789,-0.116925,0.622768,-0.887756,-0.676442,-0.40996,0.424416,-0.279859,-0.167963,...,0.967508,0.191013,1.613483,0.655958,-0.526212,0.58489,0.200618,0.538254,0.850132,1.0
3,0.281479,-0.525071,0.130746,1.69893,-0.507978,-0.954367,1.16376,1.084302,-0.574299,-0.888963,...,1.599201,1.540466,0.222635,-0.043235,0.052227,0.62466,-0.042933,0.046029,0.887284,0.0
4,0.528865,0.038423,-0.190186,0.277023,-0.382854,-0.832077,-0.439449,-0.355043,0.189325,-1.012242,...,-0.542039,-0.231946,-0.451283,0.071639,0.498077,0.633925,-1.21094,-1.14928,1.792787,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.63243,0.482682,-0.136232,0.918367,0.100855,-1.007706,-0.592897,0.257265,0.448209,-0.788035,...,-0.131837,0.501355,0.522778,0.06034,0.389447,0.19472,-0.602492,0.232616,0.702234,0.0
296,0.025844,0.165337,-0.245077,0.533705,-0.937285,-0.047996,0.29783,0.118942,-0.505983,-0.622844,...,0.8263,0.338435,1.488717,-0.550905,-0.9107,0.262096,-0.043678,-0.381346,0.096849,0.0
297,0.956626,-0.060599,-0.57058,0.763405,-1.484902,-0.810225,-0.417923,0.988698,0.071142,0.032354,...,0.875226,0.830815,1.044066,-0.348556,-0.019037,0.179124,0.17323,-0.505063,-0.331804,1.0
298,-0.008378,0.062715,-0.706405,0.500612,-0.943396,-0.004417,0.260453,0.118727,0.699558,-0.898232,...,0.580136,0.46051,0.15662,-0.441507,-0.436369,0.28289,0.526717,-0.245964,0.54091,1.0
299,1.173891,-1.19603,-0.31596,-1.20352,-0.346901,0.482871,-1.414486,-0.182644,0.4339,-1.154886,...,0.219386,-0.042042,0.952729,-0.612921,-0.182906,0.938066,-0.590468,-1.599398,1.114622,0.0

In [24]:
data=data.sample(frac=1)

In [25]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
17,0.735448,-0.170801,-0.620777,0.630827,-1.200025,-0.739741,-0.090043,0.904917,0.09269,-0.131376,...,0.97649,1.034076,1.203334,-0.291978,-0.198633,0.201105,0.042375,-0.60078,-0.369545,1.0
56,-0.402353,-0.163008,-0.641391,0.57631,-0.129987,-0.86399,0.075395,0.277617,-0.106464,-1.727753,...,1.141149,-0.900363,0.909206,0.630951,-0.228165,0.535999,0.894433,-0.239473,0.907494,0.0
30,-0.216331,0.095016,0.361364,0.503337,-1.149033,-0.037002,0.015617,0.473319,-0.635346,0.349192,...,1.293017,-0.286807,0.97754,0.364169,0.202491,1.351304,-1.433411,-0.639632,0.814412,1.0
67,0.43917,-0.504426,0.755785,1.268098,0.310198,-0.003923,-0.093277,-0.046614,-1.126243,-0.768722,...,0.229306,0.186688,-0.23142,0.420561,0.327196,1.264117,-0.92379,-0.738257,0.433829,0.0
82,0.265565,0.67058,0.019289,0.999229,-0.280109,-1.051639,1.275452,-0.216518,-0.922814,-1.686666,...,-0.338299,1.170667,0.681515,-0.682411,-0.119532,0.811132,-1.233326,0.603427,1.560027,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,1.423213,0.320603,-0.027925,0.695443,-0.565567,-0.852599,-0.143748,0.514052,0.039572,-1.702583,...,0.270232,1.096226,0.569661,-0.186221,0.041674,0.503315,0.081409,-0.46746,0.681898,0.0
186,-0.055748,1.246574,-0.424197,0.964274,-0.489151,-0.095692,0.309843,0.39625,-0.309598,-0.956764,...,1.210415,0.164447,0.782201,-0.666016,-0.056121,0.465388,-0.708831,-0.583285,0.960622,1.0
40,0.524532,-0.190707,-0.132601,-0.069479,-0.769379,-0.582056,-0.261797,0.318609,0.085813,-0.515484,...,0.716147,-0.18827,0.519076,1.08211,0.573666,0.149783,-0.199919,-0.310867,0.924846,0.0
45,-0.014736,1.681135,0.16438,0.70303,-0.278515,-1.152023,-0.703957,-0.019105,-1.086552,-0.718938,...,0.885606,0.067733,0.195498,-1.103807,-1.086814,-0.321842,-0.154798,1.332473,1.431903,0.0
208,0.047501,-1.713613,0.107329,0.711909,-0.178841,-0.770284,-0.469868,-0.022138,0.029853,0.031388,...,-0.310218,-0.647977,0.246999,-0.238644,-0.163507,0.877726,-0.128422,-0.366303,1.062325,0.0

In [26]:
data.to_csv("process1 test data after nlp(jhgan).csv")