In [1]:
import pandas as pd  

data_row=pd.read_excel('/Users/withmocha/Desktop/TEED/data/mocha/23.12.04/squat/SQUAT2.xlsx')


data_row

,Unnamed: 0,FORCE_A(Big toe),FORCE_B(Right),FORCE_C(Left),FORCE_D(Heel),FORCE_E(Little toe),FORCE_F(Center),XCOR_A(Big toe),XCOR_B(Right),XCOR_C(Left),...,YCOR_E(Little toe),YCOR_F(Center),COPX,COPY,FSR_A(Big toe),FSR_B(Right),FSR_C(Left),FSR_D(Heel),FSR_E(Little toe),FSR_F(Center)
0,NaN,6,185,276,1344,12,37,7.750000,7.408108,3.672101,...,9.0,18.648649,5.688195,21.705929,25,38,48,95,31,35
1,NaN,7,183,278,1356,15,16,7.714286,7.401639,3.604317,...,8.9,16.000000,5.688729,21.699096,24,40,48,95,30,38
2,NaN,3,203,291,1377,15,22,7.500000,7.463054,3.621993,...,8.9,17.500000,5.674755,21.616417,24,43,47,95,30,41
3,NaN,3,176,279,1367,15,14,7.500000,7.491477,3.553763,...,8.9,16.000000,5.680637,21.822546,24,44,43,95,31,44
4,NaN,0,167,259,1338,12,15,NaN,7.425150,3.619691,...,9.0,16.000000,5.709846,21.939219,22,44,41,95,33,42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
872,NaN,0,0,44,1954,0,12,NaN,NaN,3.090909,...,NaN,16.000000,5.640178,25.386723,16,34,29,128,33,33
873,NaN,0,14,51,1966,0,22,NaN,7.750000,2.950980,...,NaN,18.636364,5.626392,25.245036,16,35,27,129,31,34
874,NaN,0,12,49,1975,0,24,NaN,7.750000,2.959184,...,NaN,19.354167,5.612362,25.223287,14,35,25,129,30,34
875,NaN,0,0,47,1932,0,5,NaN,NaN,2.968085,...,NaN,16.000000,5.643072,25.364182,14,33,26,128,30,33
876,NaN,0,0,47,1932,0,5,NaN,NaN,2.968085,...,NaN,16.000000,5.643072,25.364182,14,33,26,128,30,33

In [2]:
data_row.isnull().sum()

Unnamed: 0             877
FORCE_A(Big toe)         0
FORCE_B(Right)           0
FORCE_C(Left)            0
FORCE_D(Heel)            0
FORCE_E(Little toe)      0
FORCE_F(Center)          0
XCOR_A(Big toe)        844
XCOR_B(Right)          380
XCOR_C(Left)            19
XCOR_D(Heel)             0
XCOR_E(Little toe)     840
XCOR_F(Center)         117
YCOR_A(Big toe)        844
YCOR_B(Right)          380
YCOR_C(Left)            19
YCOR_D(Heel)             0
YCOR_E(Little toe)     840
YCOR_F(Center)         117
COPX                     0
COPY                     0
FSR_A(Big toe)           0
FSR_B(Right)             0
FSR_C(Left)              0
FSR_D(Heel)              0
FSR_E(Little toe)        0
FSR_F(Center)            0
dtype: int64

In [3]:
data_row.fillna(method="ffill",inplace=True)

/var/folders/gb/hslcbzfs0bvcnj3zxtfrxt_r0000gn/T/ipykernel_92391/2738689939.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_row.fillna(method="ffill",inplace=True)

In [4]:
data_row.isnull().sum()

Unnamed: 0             877
FORCE_A(Big toe)         0
FORCE_B(Right)           0
FORCE_C(Left)            0
FORCE_D(Heel)            0
FORCE_E(Little toe)      0
FORCE_F(Center)          0
XCOR_A(Big toe)          0
XCOR_B(Right)            0
XCOR_C(Left)             0
XCOR_D(Heel)             0
XCOR_E(Little toe)       0
XCOR_F(Center)           0
YCOR_A(Big toe)          0
YCOR_B(Right)            0
YCOR_C(Left)             0
YCOR_D(Heel)             0
YCOR_E(Little toe)       0
YCOR_F(Center)           0
COPX                     0
COPY                     0
FSR_A(Big toe)           0
FSR_B(Right)             0
FSR_C(Left)              0
FSR_D(Heel)              0
FSR_E(Little toe)        0
FSR_F(Center)            0
dtype: int64

In [5]:
data_row.isnull().sum()

Unnamed: 0             877
FORCE_A(Big toe)         0
FORCE_B(Right)           0
FORCE_C(Left)            0
FORCE_D(Heel)            0
FORCE_E(Little toe)      0
FORCE_F(Center)          0
XCOR_A(Big toe)          0
XCOR_B(Right)            0
XCOR_C(Left)             0
XCOR_D(Heel)             0
XCOR_E(Little toe)       0
XCOR_F(Center)           0
YCOR_A(Big toe)          0
YCOR_B(Right)            0
YCOR_C(Left)             0
YCOR_D(Heel)             0
YCOR_E(Little toe)       0
YCOR_F(Center)           0
COPX                     0
COPY                     0
FSR_A(Big toe)           0
FSR_B(Right)             0
FSR_C(Left)              0
FSR_D(Heel)              0
FSR_E(Little toe)        0
FSR_F(Center)            0
dtype: int64

In [6]:
data_row.drop(columns=["Unnamed: 0"],inplace=True)

In [7]:
data_row.isnull().sum()

FORCE_A(Big toe)       0
FORCE_B(Right)         0
FORCE_C(Left)          0
FORCE_D(Heel)          0
FORCE_E(Little toe)    0
FORCE_F(Center)        0
XCOR_A(Big toe)        0
XCOR_B(Right)          0
XCOR_C(Left)           0
XCOR_D(Heel)           0
XCOR_E(Little toe)     0
XCOR_F(Center)         0
YCOR_A(Big toe)        0
YCOR_B(Right)          0
YCOR_C(Left)           0
YCOR_D(Heel)           0
YCOR_E(Little toe)     0
YCOR_F(Center)         0
COPX                   0
COPY                   0
FSR_A(Big toe)         0
FSR_B(Right)           0
FSR_C(Left)            0
FSR_D(Heel)            0
FSR_E(Little toe)      0
FSR_F(Center)          0
dtype: int64

In [8]:
data_row.to_excel("squat_data.xlsx")