In [1]:
import pandas as pd

data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/final/normal/normal data(0528).csv",index_col=0)
data_ab1=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/final/abnormal/대출사기형(10문장).csv",index_col=0)
data_ab2=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/final/abnormal/수사기관형(10문장).csv",index_col=0)

In [2]:
data=data.sample(frac=1)

In [3]:
data_ab1

                                              sentence  predict
0    여보세요 네   님 예 예 어저께 통화했던 최영환입니다 아 예 예 어떻게 가진행 결...        1
1     5년이고요 네 매 월 상환하시는 금액은 60개월 기준 원금 이자 포함되신 금액으로...        1
2     말씀하세요 아니 괜찮으시냐고요? 아 예 예 그럼 간단하게 상품 설명부터 드릴게요....        1
3     뭐 이게 좀 어려우실 경우에는 저희 은행 쪽으로 위임 처리하시는 방법도 있으시니까...        1
4     위임하실 경우에는 방문이나 내방 없이 드리는 전화 받으시고 녹취를 통해서 대출 계...        1
..                                                 ...      ...
553   네 납부가 완료 되셨잖아요 그럼 그쪽 전산망으로 이제 고객센터한테 보내야 돼요 서...        1
554   네 사기치지 마시고요 다른사람한테 피해주지 마시구요 그러다 벌받아요 무슨소리하시는...        1
555   네 ㅇㅇ 맞으신가요? 네네 네 안녕하세요 여기 스포츠 토토 싸이트인데요 네 다름이...        1
556   아... 돈은 만약에 하면 어떻게 받는거에요? 저희는 그 손님들 게임머니 펀드용으...        1
557   네 여보세요 뭐 어디세요? 아 네 안녕하세요 저희 그 하나캐피탈에서 연락을 드렸습...        1

[558 rows x 2 columns]

In [4]:
data_ab2

                                               sentence  predict
0     아 서울 중앙 지검 첨단 범죄 수사 일부 이희나 수사관입니다. 본 사건 조사는 법원...        2
1      네 본인 김성오 일당 잘 알고 있으십니까? 아니요 전혀 모른다고 진술 하셨는데 맞...        2
2      네 이 사건은 전자 금융 거래법 위반 금융 범죄 사기 사건으로 다수의 피해자가 발...        2
3      국민 은행에.. 국민 은행에.. 휴먼 계좌도 다 얘기 해야 하나요? 예 예 예 국...        2
4      아이 사랑 카드 아 그러면은 국민 카드 국민 은행 농협 은행 신한 은행 외에는 본...        2
...                                                 ...      ...
1269   네 수고하셨습니다 네41세 김명식이요? 모르는데요? 김용식. 용식 연식? 김용식....        2
1270   모르는 사람인데요 전혀 모르세요? 네 아 현재 검찰에서 그 김용식 주범으로 인한 ...        2
1271   본인께서 광명시 쪽 가셔서 금융권 업무 보신 거 아니세요? 네 아 본인께서는 지금...        2
1272   본인이 아시는지 모르시는지 조사를 해봐야 아는 거죠. 그거는 그니까 만약에... ...        2
1273   네 그렇게 할게요. 어디로 출석하면 될까요 서울시 서초구로 오시면 됩니다 서울시오...        2

[1274 rows x 2 columns]

In [5]:
data_ab2['predict']=1

In [6]:
data_ab2

                                               sentence  predict
0     아 서울 중앙 지검 첨단 범죄 수사 일부 이희나 수사관입니다. 본 사건 조사는 법원...        1
1      네 본인 김성오 일당 잘 알고 있으십니까? 아니요 전혀 모른다고 진술 하셨는데 맞...        1
2      네 이 사건은 전자 금융 거래법 위반 금융 범죄 사기 사건으로 다수의 피해자가 발...        1
3      국민 은행에.. 국민 은행에.. 휴먼 계좌도 다 얘기 해야 하나요? 예 예 예 국...        1
4      아이 사랑 카드 아 그러면은 국민 카드 국민 은행 농협 은행 신한 은행 외에는 본...        1
...                                                 ...      ...
1269   네 수고하셨습니다 네41세 김명식이요? 모르는데요? 김용식. 용식 연식? 김용식....        1
1270   모르는 사람인데요 전혀 모르세요? 네 아 현재 검찰에서 그 김용식 주범으로 인한 ...        1
1271   본인께서 광명시 쪽 가셔서 금융권 업무 보신 거 아니세요? 네 아 본인께서는 지금...        1
1272   본인이 아시는지 모르시는지 조사를 해봐야 아는 거죠. 그거는 그니까 만약에... ...        1
1273   네 그렇게 할게요. 어디로 출석하면 될까요 서울시 서초구로 오시면 됩니다 서울시오...        1

[1274 rows x 2 columns]

In [7]:
data_ab=pd.concat([data_ab1,data_ab2])

In [8]:
data_ab

                                               sentence  predict
0     여보세요 네   님 예 예 어저께 통화했던 최영환입니다 아 예 예 어떻게 가진행 결...        1
1      5년이고요 네 매 월 상환하시는 금액은 60개월 기준 원금 이자 포함되신 금액으로...        1
2      말씀하세요 아니 괜찮으시냐고요? 아 예 예 그럼 간단하게 상품 설명부터 드릴게요....        1
3      뭐 이게 좀 어려우실 경우에는 저희 은행 쪽으로 위임 처리하시는 방법도 있으시니까...        1
4      위임하실 경우에는 방문이나 내방 없이 드리는 전화 받으시고 녹취를 통해서 대출 계...        1
...                                                 ...      ...
1269   네 수고하셨습니다 네41세 김명식이요? 모르는데요? 김용식. 용식 연식? 김용식....        1
1270   모르는 사람인데요 전혀 모르세요? 네 아 현재 검찰에서 그 김용식 주범으로 인한 ...        1
1271   본인께서 광명시 쪽 가셔서 금융권 업무 보신 거 아니세요? 네 아 본인께서는 지금...        1
1272   본인이 아시는지 모르시는지 조사를 해봐야 아는 거죠. 그거는 그니까 만약에... ...        1
1273   네 그렇게 할게요. 어디로 출석하면 될까요 서울시 서초구로 오시면 됩니다 서울시오...        1

[1832 rows x 2 columns]

In [9]:
abnormal_data=data_ab

In [10]:
process1_data=pd.concat([data,abnormal_data])

In [11]:
process1_data=process1_data.sample(frac=1)

In [12]:
process1_data

                                               sentence  predict
642   2층 카페내 세미나실은 4인정원이라 외부에 있는 세미나실로 예약도와드려도 괜찮을까요...        0
1235   이경호 계장님이요. 예 알겠습니다 예통장명이  계좌 맞구요? 그리고 통장 발급 일...        1
1831  어떤 점이 궁금하신가요?모바일 검색창에 "자동차세 계산기"를 검색하셔도 자동차세 조...        0
532    일단은 저희가 절차를 하고 나중에 잠시 동안 일시적으로 이제 맞춤형 상의할 수가 ...        1
355   혹시 개인택시입니까?기본금리에서 이차보전 금리를 차감한 본인 부담 금리가 1%이하인...        0
...                                                 ...      ...
66     매 월 상환이 그렇죠? 원금 예 그럼 뭐 바로 해야겠네. 가가지고 시간 또 걸리고...        1
2124  절차가 궁금하십니까?입급은행을 '지방세입'으로 선택하고 고지서에 기재된 지방세입계좌...        0
1234   서울지검어디세요 첨단 범죄 수사 2부입니다 예? 첨단범죄수사 2부에 이경호요 이경...        1
212    아니에요. 유선상으로 대출할 때는 찾아가는 거는 최하위 우선 순위 실행입니다 음 ...        1
1063  언제부턴지 아시나요?네, 청년포털에서 정보 변경하실 수 있습니다. 크린넷시설같다는 ...        0

[4080 rows x 2 columns]

In [13]:
process1_test_data=process1_data[:300]
process1_train_data=process1_data[300:]

In [14]:
process1_train_data

                                               sentence  predict
297   기간은 몇 년으로 되어있으신가요?대리수령시 신청인 신분증과 대리인신분증, 접수증 있...        0
2232  지역이 어디신가요?연말정산은 매년 2월에 실시합니다.출력사유가 어떻게 되시나요?올해...        0
685   올 해 지급기준이 몇프로인가요?네 가능해요. 이직할때 회사가 너무 멀리이사가서 그런...        0
1922   네  어떤것이 궁금한가요?신청하시면 4년간 유예 되십니다. 소상공인 이신가요?대출...        0
909   바꿔주실 수 있나요?7일 미만일 경우 만원입니다. 네 여보세요?네, 신고와 함께 즉...        0
...                                                 ...      ...
66     매 월 상환이 그렇죠? 원금 예 그럼 뭐 바로 해야겠네. 가가지고 시간 또 걸리고...        1
2124  절차가 궁금하십니까?입급은행을 '지방세입'으로 선택하고 고지서에 기재된 지방세입계좌...        0
1234   서울지검어디세요 첨단 범죄 수사 2부입니다 예? 첨단범죄수사 2부에 이경호요 이경...        1
212    아니에요. 유선상으로 대출할 때는 찾아가는 거는 최하위 우선 순위 실행입니다 음 ...        1
1063  언제부턴지 아시나요?네, 청년포털에서 정보 변경하실 수 있습니다. 크린넷시설같다는 ...        0

[3780 rows x 2 columns]

In [15]:
process1_test_data

                                               sentence  predict
642   2층 카페내 세미나실은 4인정원이라 외부에 있는 세미나실로 예약도와드려도 괜찮을까요...        0
1235   이경호 계장님이요. 예 알겠습니다 예통장명이  계좌 맞구요? 그리고 통장 발급 일...        1
1831  어떤 점이 궁금하신가요?모바일 검색창에 "자동차세 계산기"를 검색하셔도 자동차세 조...        0
532    일단은 저희가 절차를 하고 나중에 잠시 동안 일시적으로 이제 맞춤형 상의할 수가 ...        1
355   혹시 개인택시입니까?기본금리에서 이차보전 금리를 차감한 본인 부담 금리가 1%이하인...        0
...                                                 ...      ...
698    네 작성하셨죠? 네 네 그러면 손가락 한 마디 정도 밑으로 내려오셔가지고요 네 네...        1
791    네 네 그리고 차후에 2차 피해라든지 3차 피해가 일어난다면 최고 5천만 원 한도...        1
582    예 질문드리기 앞서서 수사 기관에서는 개인의 개인 정보나 금융 정보에 대해선 일체...        1
1574  어떤 궁금증이 있으신가요부양의무자가 없거나, 있어도 부양능력이 없거나 또는 부양을 ...        0
1407  네 거주지가 어디신지 여쭈어봐도 되겠습니까?네, 이체증을 확인 후 입금됩니다. 더 ...        0

[300 rows x 2 columns]

In [16]:
process1_train_data.to_csv("process 1 train data row.csv")
process1_test_data.to_csv("process 1 test data row.csv")