In [1]:
import pandas as pd 

data_main=pd.read_excel("/Users/withmocha/Desktop/TEED/data/mocha/23.11.14/SBC/gait_main.xlsx")

data_main

,Unnamed: 0,FORCE,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,X COORDINATE,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,d2t(FSR divided by mass DATA),Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,NaN,A(Big toe),B(Right),C(Left),D(Heel),E(Little toe),F(Center),A(Big toe),B(Right),C(Left),...,C(Left),D(Heel),E(Little toe),F(Center),A(Big toe),B(Right),C(Left),D(Heel),E(Little toe),F(Center)
1,14.0,0,0,0,14,0,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,112.0,0,0,0,109,0,3,NaN,NaN,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,358.0,0,0,0,240,0,118,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,324.0,0,0,0,324,0,0,NaN,NaN,NaN,...,0,0.936508,0,0,0.809524,0,0,0.936508,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
597,676.0,385,96,36,0,159,0,7.380519,7.90625,2.722222,...,0,0,-0.190476,0,0.079365,0,0,0,0.015873,0
598,470.0,278,53,22,0,117,0,7.316547,7.924528,2.704545,...,0,0,-0.174603,0,0.079365,0,0,0,0.015873,0
599,263.0,170,16,0,0,77,0,7.373529,8.03125,NaN,...,0,0,-0.190476,0,0.047619,0,0,0,-0.015873,0
600,157.0,105,6,0,0,46,0,7.261905,8,NaN,...,0,0,-0.174603,0,0.047619,0,0,0,0.015873,0
601,224.0,40,0,0,0,28,156,7.35,NaN,NaN,...,0,0,-0.888889,0,0.047619,0,0,0,-0.714286,0

In [3]:
data_row=pd.read_excel("/Users/withmocha/Desktop/TEED/data/mocha/23.11.14/gait_row.xlsx")

data_row

,Force_A(Big toe),Force_B(Right),Force_C(Left),Force_D(Heel),E(LittleForce_ toe),Force_F(Center),X_COR_A(Big toe),Force_B(Right).1,Force_C(Left).1,Force_D(Heel).1,Force_E(Little toe),Force_F(Center).1,Y_COR_A(Big toe),Y_COR_B(Right),Y_COR_C(Left),Y_COR_D(Heel),Y_COR_E(Little toe),Y_COR_F(Center)
0,0,0,0,14,0,0,NaN,NaN,NaN,6.750000,NaN,NaN,NaN,NaN,NaN,25.28571,NaN,NaN
1,0,0,0,109,0,3,NaN,NaN,NaN,6.183486,NaN,5.0,NaN,NaN,NaN,25.55505,NaN,16.5
2,0,0,0,240,0,118,NaN,NaN,NaN,5.900000,NaN,5.0,NaN,NaN,NaN,25.70625,NaN,16.0
3,0,0,0,324,0,0,NaN,NaN,NaN,5.865741,NaN,NaN,NaN,NaN,NaN,25.72531,NaN,NaN
4,0,0,0,412,0,0,NaN,NaN,NaN,5.810680,NaN,NaN,NaN,NaN,NaN,25.71723,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,385,96,36,0,159,0,7.380519,7.906250,2.722222,NaN,5.012579,NaN,1.958505,9.619792,9.888889,NaN,8.320755,NaN
597,278,53,22,0,117,0,7.316547,7.924528,2.704545,NaN,5.012821,NaN,2.032201,9.603774,9.931818,NaN,8.290598,NaN
598,170,16,0,0,77,0,7.373529,8.031250,NaN,NaN,5.123377,NaN,2.073930,9.500000,NaN,NaN,8.188312,NaN
599,105,6,0,0,46,0,7.261905,8.000000,NaN,NaN,5.130435,NaN,2.118211,9.500000,NaN,NaN,8.206522,NaN
600,40,0,0,0,28,156,7.350000,NaN,NaN,NaN,5.142857,5.0,2.562500,NaN,NaN,NaN,8.214286,16.0

In [ ]:
g