In [1]:
import pandas as pd

data=pd.read_csv("/Users/withmocha/Desktop/DATA/Capston Design(2024)/data(sentence)/0410/0506/origin train data.csv",index_col=0)

In [2]:
data

                                        sentence  predict
4816    '네 하이픈 마이너스 표시 하나 하시고 사건 파일 보고서라고 적어주세요'        1
8209                             네, 그렇게 하셔도 됩니다.        0
16297                      네 잠시만요 한번 확인 해 보겠습니다.        0
8012              '제가 그럼 전화를 좀 이따 다시 드려도 괜찮을까요?'        1
1463               '아 그러면 부산 은행은 쉽게 말해서 입출금이에요?'        1
...                                          ...      ...
18510                   네. 대리인 신청시에는 서류가 다르겠습니다.        0
1783                    ' 저 아까 어디소속 누구라고 말씀하셨죠?'        1
8762    수업에 관한건 하지 않습니다.자유롭게 과제나 개인 공부를 하기도 합니다.        0
8238                    '녹취록 단말기고 수사 전용 단말기인데요.'        1
6597                연예인 사건 그리고 본인이 속해있는 금융 사기 사건        1

[28842 rows x 2 columns]

In [3]:
data=data.sample(frac=1)

In [4]:
data

                                                sentence  predict
11810                                 행정복지센타에 신청하시면 됩니다.        0
12912                           심각단계에서 경계단계로 내려올때 까지 입니다        0
3415                                 '제가 들은 부분을 설명하라고요?'        1
1110                            실업급여 수령이 종료되면 신청 가능합니다.         0
17183        지방세가 부과 또는 징수에 이의가 있을 때 구제 받을 수 있는 제도되겠습니다.        0
...                                                  ...      ...
5112    전월세보증금지원센터에 전화 또는 방문해 상담을 받은 후 절차에 따라 신청하시면 됩니다.        0
1761                            '왜냐면 솔직히 이게 보이스피싱 같기도 하고        1
14610  고객님 만일 동시에 청약 신청할 경우 추첨시 무효처리 또는 당첨취소 등의  불이익을...        0
7405                                  3년 안쪽으로라고 적어드릴거구요'        1
16368                     구로구청 홈페이지에 들어가시면 확인 하실 수 있습니다.        0

[28842 rows x 2 columns]

In [5]:
data.to_csv("binary train_data_before_vector.csv")

In [6]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')

In [7]:
data.isnull().sum()

sentence    0
predict     0
dtype: int64

In [8]:
A=model.encode(data.iloc[0,0])

In [9]:
A.shape[0]

768

In [10]:
list=[]

for i in range(A.shape[0]):
    list.append(i)

In [11]:
list

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767]

In [12]:
x_train=pd.DataFrame(index=range(0,data.shape[0]),columns=list)

In [13]:
x_train.shape

(28842, 768)

In [14]:

y_train=pd.DataFrame(index=range(0,x_train.shape[0]),columns=['predict'])

In [15]:

x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28838,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
y_train

      predict
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
...       ...
28837     NaN
28838     NaN
28839     NaN
28840     NaN
28841     NaN

[28842 rows x 1 columns]

In [17]:
for i in range(data.shape[0]):
    y_train.iloc[i,0]=data.iloc[i,1]

In [18]:
y_train

      predict
0           0
1           0
2           1
3           0
4           0
...       ...
28837       0
28838       1
28839       0
28840       1
28841       0

[28842 rows x 1 columns]

In [19]:
y_train.isnull().sum()

predict    0
dtype: int64

In [20]:
for i in range(data.shape[0]):
    vector=[]
    vector=model.encode(data.iloc[i,0])
    for j in range(x_train.shape[1]):
        x_train.iloc[i,j]=vector[j]

In [21]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,0.006798,-0.071722,-0.005703,-0.019025,0.007538,-0.028805,-0.029757,0.032886,0.050502,-0.017158,...,-0.06832,-0.041402,-0.010655,-0.012882,-0.019582,-0.031766,0.011213,0.022461,0.036005,-0.025895
1,0.060642,-0.003776,-0.014648,0.016415,0.041357,-0.001738,-0.091098,0.022007,0.091218,0.014787,...,-0.008969,0.010193,0.045736,-0.025204,-0.067704,-0.033122,-0.012506,0.017731,0.033685,-0.056391
2,0.113083,-0.05919,-0.015329,0.001105,0.02156,0.003139,-0.026794,0.015624,0.06996,-0.014575,...,0.019937,-0.018354,-0.023291,0.029543,-0.041187,-0.055788,-0.017954,0.032724,-0.002659,-0.014032
3,0.031246,-0.065806,-0.008099,0.008748,0.026631,-0.010195,-0.041112,0.001881,0.044373,-0.014551,...,-0.043216,-0.028334,0.005691,0.002833,-0.042561,-0.054128,0.007638,0.041549,0.019703,-0.019924
4,0.055225,-0.048069,0.00179,0.001389,0.02852,-0.004947,-0.02869,-0.003125,0.063008,-0.018724,...,-0.026645,-0.025351,0.02649,0.014794,-0.057974,-0.093751,0.006481,0.022529,0.027503,-0.020578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28837,0.028164,-0.084771,-0.016415,-0.019199,-0.005638,-0.015935,0.00772,-0.012381,0.057028,-0.019605,...,-0.043225,-0.041415,-0.01464,0.01201,-0.025954,-0.038281,0.02829,0.031703,0.012972,-0.014402
28838,0.07479,-0.054248,-0.027854,0.012066,0.04132,-0.01101,-0.015067,0.013427,0.049772,-0.000545,...,-0.039442,-0.008972,-0.009839,-0.001482,-0.027978,-0.038922,0.031171,0.027696,0.04058,-0.024878
28839,0.040861,-0.089185,-0.031374,-0.025319,-0.013003,-0.00388,0.027415,-0.011801,0.060524,-0.013711,...,-0.048208,-0.04657,-0.026116,0.015368,-0.030752,-0.053538,0.023176,0.015972,-0.000455,-0.018152
28840,0.110344,-0.054362,-0.019661,-0.007657,0.009812,0.006971,-0.033478,0.034213,0.048547,-0.030901,...,-0.036442,-0.022981,-0.018597,0.004869,-0.045659,-0.034232,0.002719,0.043484,-0.000361,-0.025221
28841,0.049537,-0.077962,-0.01808,-0.028968,0.011608,-0.001888,0.01602,-0.010358,0.0602,-0.018422,...,-0.046362,-0.051734,-0.001668,0.01914,-0.043058,-0.055497,0.019571,0.007444,0.020961,-0.016584

In [22]:
data=pd.concat([x_train,y_train],axis=1)

In [23]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
0,0.006798,-0.071722,-0.005703,-0.019025,0.007538,-0.028805,-0.029757,0.032886,0.050502,-0.017158,...,-0.041402,-0.010655,-0.012882,-0.019582,-0.031766,0.011213,0.022461,0.036005,-0.025895,0
1,0.060642,-0.003776,-0.014648,0.016415,0.041357,-0.001738,-0.091098,0.022007,0.091218,0.014787,...,0.010193,0.045736,-0.025204,-0.067704,-0.033122,-0.012506,0.017731,0.033685,-0.056391,0
2,0.113083,-0.05919,-0.015329,0.001105,0.02156,0.003139,-0.026794,0.015624,0.06996,-0.014575,...,-0.018354,-0.023291,0.029543,-0.041187,-0.055788,-0.017954,0.032724,-0.002659,-0.014032,1
3,0.031246,-0.065806,-0.008099,0.008748,0.026631,-0.010195,-0.041112,0.001881,0.044373,-0.014551,...,-0.028334,0.005691,0.002833,-0.042561,-0.054128,0.007638,0.041549,0.019703,-0.019924,0
4,0.055225,-0.048069,0.00179,0.001389,0.02852,-0.004947,-0.02869,-0.003125,0.063008,-0.018724,...,-0.025351,0.02649,0.014794,-0.057974,-0.093751,0.006481,0.022529,0.027503,-0.020578,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28837,0.028164,-0.084771,-0.016415,-0.019199,-0.005638,-0.015935,0.00772,-0.012381,0.057028,-0.019605,...,-0.041415,-0.01464,0.01201,-0.025954,-0.038281,0.02829,0.031703,0.012972,-0.014402,0
28838,0.07479,-0.054248,-0.027854,0.012066,0.04132,-0.01101,-0.015067,0.013427,0.049772,-0.000545,...,-0.008972,-0.009839,-0.001482,-0.027978,-0.038922,0.031171,0.027696,0.04058,-0.024878,1
28839,0.040861,-0.089185,-0.031374,-0.025319,-0.013003,-0.00388,0.027415,-0.011801,0.060524,-0.013711,...,-0.04657,-0.026116,0.015368,-0.030752,-0.053538,0.023176,0.015972,-0.000455,-0.018152,0
28840,0.110344,-0.054362,-0.019661,-0.007657,0.009812,0.006971,-0.033478,0.034213,0.048547,-0.030901,...,-0.022981,-0.018597,0.004869,-0.045659,-0.034232,0.002719,0.043484,-0.000361,-0.025221,1
28841,0.049537,-0.077962,-0.01808,-0.028968,0.011608,-0.001888,0.01602,-0.010358,0.0602,-0.018422,...,-0.051734,-0.001668,0.01914,-0.043058,-0.055497,0.019571,0.007444,0.020961,-0.016584,0

In [24]:
data=data.sample(frac=1)

In [25]:
data

,0,1,2,3,4,5,6,7,8,9,...,759,760,761,762,763,764,765,766,767,predict
28636,0.057666,-0.048499,-0.015004,-0.008556,0.00748,0.004326,-0.044761,0.025557,0.058081,0.001161,...,-0.04209,-0.001205,-0.00647,-0.05217,-0.051578,0.010536,0.03311,0.026323,-0.023366,0
5242,0.084339,-0.016759,-0.002239,0.006603,0.034535,-0.0001,-0.025028,0.011796,0.03749,0.035441,...,-0.049235,-0.034401,-0.019802,-0.064542,-0.005789,0.011845,0.0175,0.00893,-0.02424,1
9597,0.048915,-0.082816,-0.022027,-0.036624,-0.00934,0.00521,0.010473,-0.008542,0.076122,-0.014251,...,-0.047595,-0.029653,0.028283,-0.031656,-0.046234,0.021212,0.019049,0.003998,-0.011915,0
7582,0.04478,-0.074579,-0.025775,-0.022203,-0.012583,-0.003432,0.012088,-0.006128,0.052249,-0.011539,...,-0.03972,-0.020792,0.019995,-0.030663,-0.046267,0.017612,0.020224,0.004303,-0.022597,0
4625,0.046568,-0.084928,-0.012517,-0.023174,0.001471,-0.001228,-0.020728,0.006802,0.053653,-0.001821,...,-0.043898,-0.015343,0.008613,-0.034361,-0.034957,0.008622,0.016759,0.001847,-0.01697,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5680,0.012926,-0.054298,-0.018591,0.020354,0.024776,-0.015096,-0.047258,0.038192,0.053365,0.003048,...,-0.023678,0.017794,-0.031177,-0.03903,-0.067405,0.022877,0.015605,0.020549,-0.031647,0
22362,0.083671,-0.068238,-0.02411,-0.003436,0.063956,0.005678,-0.046681,0.034365,0.021408,-0.003563,...,-0.007964,-0.065795,0.0145,-0.01818,0.047096,-0.031353,0.023866,0.004741,-0.000127,1
26489,0.1125,-0.015669,-0.019522,0.001867,0.01456,0.009811,-0.032503,0.053587,0.075874,-0.005853,...,-0.024218,-0.025601,0.049616,-0.031445,-0.001811,-0.016349,0.03134,0.0161,0.000723,1
21277,0.063781,-0.045069,-0.021233,0.004045,0.035538,0.01352,-0.06087,0.017398,0.066957,-0.018462,...,-0.029354,0.011228,-0.001308,-0.058188,-0.06816,0.005134,0.026979,0.031734,-0.012957,0
12871,0.069192,0.002381,0.001885,0.025675,0.030192,-0.010695,-0.005921,0.026005,0.035557,0.006328,...,-0.055183,-0.049386,-0.036761,-0.043909,-0.040482,0.025306,0.05662,-0.008342,0.000787,0

In [26]:
data.to_csv("binary train_data_after_vector(0506).csv")